"""Golden master: the whole simulator against a hand-computed 5-bar short-side scenario.

Every fill, commission, carry accrual, the dividend debit, and cash and NAV per bar are
asserted line by line. Ground truth is test_the_golden_master.hand.txt, produced by a
standalone calculator that does not import this codebase.

The .hand.json file
-------------------
A fill is reported as `(ts, instrument_id, qty, price, trade_cost)`, where `trade_cost` is
the sum of commission and spread, so fills alone would not catch $6.00 moving from
`IBKRCommission` to `PercentOfNotionalSpread`. Borrow, margin interest and the dividend
reach the result only through the cash and equity curves, which cannot tell them apart.
`BacktestResult` (src/backtest_framework/engine/backtest.py) has no per-brick attribution,
so the decomposition exists only in the hand ledger. `test_the_golden_master.hand.json` is
that ledger in machine-readable form, transcribed by hand from the .hand.txt and not
generated by the engine.

Three tests check the transcription:

1. `test_the_closed_book_recomputation_reproduces_every_hand_value` recomputes all 19
   fields of all 5 bars from the scenario block with stdlib arithmetic.
2. `test_every_hand_value_appears_in_the_hand_file` requires each number, in the
   .hand.txt's own notation, to appear in the .hand.txt.
3. `test_the_cash_curve_carries_the_carry_the_engine_never_reports` reads the carry and
   the dividend from the cash curve and checks their per-bar sum against the ledger.

Borrow and margin interest within one bar cannot be separated from outside the engine:
both are same-sign cash deductions at the same instant. The hand ledger and the
closed-book calculator split them.
"""

from __future__ import annotations

import ast
import inspect
import json
import textwrap
from datetime import datetime
from pathlib import Path

import pytest

from backtest_framework.costs.bricks import PercentOfNotionalSpread
from backtest_framework.costs.equity_bricks import BorrowFee, DividendFlow, IBKRCommission, MarginInterest
from backtest_framework.costs.stack import CostStack
from backtest_framework.data.bars import TimestampedBar
from backtest_framework.engine.allocator import ConstantSplitAllocator
from backtest_framework.engine.backtest import BacktestResult, run_backtest
from backtest_framework.engine.strategy import ScheduledWeightStrategy
from backtest_framework.instruments.equity import Equity
from backtest_framework.simulator.fills import Bar

TOLERANCE = 1e-6  # relative tolerance for golden comparisons

HERE = Path(__file__).resolve().parent
HAND_JSON = HERE / "test_the_golden_master.hand.json"
HAND_TXT = HERE / "test_the_golden_master.hand.txt"

HAND = json.loads(HAND_JSON.read_text(encoding="utf-8"))
SCENARIO = HAND["scenario"]
BARS = HAND["bars"]

# Timestamps come from the ledger rather than Python literals, so the engine's scenario and
# the ledger's cannot diverge.
THU, FRI, MON, TUE, WED = (datetime.fromisoformat(t) for t in SCENARIO["timestamps"])

# Every per-bar field in the ledger. A field added to the JSON but not reproduced by the
# closed-book calculator fails the recomputation test.
LEDGER_FIELDS = (
    "price",
    "days",
    "qty_before",
    "qty_after",
    "delta",
    "notional",
    "commission",
    "spread",
    "trade_cost",
    "short_notional",
    "borrow",
    "margin_base",
    "margin_interest",
    "dividend",
    "nav_snapshot",
    "nav_post_carry",
    "cash",
    "nav",
)


def _bar(price: float) -> Bar:
    return Bar(open=price, high=price, low=price, close=price)


@pytest.fixture(scope="module")
def result():
    """The engine's run of the scenario the hand ledger describes, with its parameters."""
    commission = SCENARIO["commission"]
    dividend = SCENARIO["dividend"]
    bars = {
        "TEST": [
            TimestampedBar(datetime.fromisoformat(ts), _bar(close))
            for ts, close in zip(SCENARIO["timestamps"], SCENARIO["closes"])
        ]
    }
    stack = CostStack(
        trade_bricks=(
            IBKRCommission(
                per_share=commission["per_share"],
                min_per_order=commission["minimum"],
                max_pct_of_trade_value=commission["cap_frac"],
            ),
            PercentOfNotionalSpread(bps=SCENARIO["spread_bps"]),
        ),
        carry_bricks=(BorrowFee(annual_rate=SCENARIO["borrow_annual"]),),
        portfolio_carry_bricks=(MarginInterest(annual_rate=SCENARIO["margin_annual"]),),
        event_flow_bricks=(
            DividendFlow(
                dividends_by_symbol={
                    SCENARIO["symbol"]: (
                        (datetime.fromisoformat(dividend["ex"]), dividend["per_share"]),
                    )
                }
            ),
        ),
    )
    strategy = ScheduledWeightStrategy(
        strategy_id="s", weights_by_instrument={SCENARIO["symbol"]: list(SCENARIO["weights"])}
    )
    return run_backtest(
        bars_by_instrument=bars,
        instruments={SCENARIO["symbol"]: Equity(symbol=SCENARIO["symbol"])},
        strategies=[strategy],
        cost_stack=stack,
        allocator=ConstantSplitAllocator(),
        starting_cash=SCENARIO["starting_cash"],
    )


# --------------------------------------------------------------- the closed-book calculator


def recompute(scenario: dict) -> list[dict]:
    """Walk the scenario bar by bar in stdlib arithmetic.

    Must not use `backtest_framework`; a calculator that called the cost bricks would agree
    with them by construction. `test_the_closed_book_calculator_never_reaches_for_the_engine`
    enforces this.

    Order of operations, as in the hand file's "Engine order per bar" line: snapshot at this
    bar's close on the previous bar's cash -> per-leg borrow and dividend -> portfolio
    margin -> re-size at the post-carry NAV -> fill at the close.
    """
    per_share = scenario["commission"]["per_share"]
    minimum = scenario["commission"]["minimum"]
    cap_frac = scenario["commission"]["cap_frac"]
    bps = scenario["spread_bps"]
    ex_date = datetime.fromisoformat(scenario["dividend"]["ex"])
    per_share_dividend = scenario["dividend"]["per_share"]

    cash = scenario["starting_cash"]
    qty = 0.0
    previous: datetime | None = None
    out: list[dict] = []

    for index, (raw_ts, price, weight) in enumerate(
        zip(scenario["timestamps"], scenario["closes"], scenario["weights"])
    ):
        timestamp = datetime.fromisoformat(raw_ts)
        days = None if previous is None else (timestamp - previous).days
        borrow = margin_interest = dividend = 0.0
        short_notional = margin_base = 0.0

        if previous is None:
            # No previous bar, no carry step: the sizing NAV is the starting cash.
            nav_snapshot = cash + qty * price
        else:
            nav_snapshot = cash + qty * price
            if qty != 0.0:
                short_notional = -qty * price if qty < 0.0 else 0.0
                borrow = scenario["borrow_annual"] * short_notional * days / 365.0
                cash -= borrow
                if previous < ex_date <= timestamp:
                    # A short pays the dividend to the lender: negative on a negative
                    # quantity.
                    dividend = qty * per_share_dividend
                    cash += dividend
            margin_base = max(abs(qty) * price - nav_snapshot, 0.0)
            margin_interest = scenario["margin_annual"] * margin_base * days / 365.0
            cash -= margin_interest

        nav_post_carry = cash + qty * price
        desired = float(round(weight * nav_post_carry / price))  # whole shares
        delta = desired - qty
        notional = abs(delta) * price
        commission = (
            min(max(per_share * abs(delta), minimum), cap_frac * notional) if delta != 0.0 else 0.0
        )
        spread = bps / 10_000.0 * notional
        trade_cost = commission + spread
        cash -= delta * price + trade_cost

        out.append(
            {
                "index": index,
                "timestamp": raw_ts,
                "price": price,
                "days": days,
                "qty_before": qty,
                "qty_after": desired,
                "delta": delta,
                "notional": notional,
                "commission": commission,
                "spread": spread,
                "trade_cost": trade_cost,
                "short_notional": short_notional,
                "borrow": borrow,
                "margin_base": margin_base,
                "margin_interest": margin_interest,
                "dividend": dividend,
                "nav_snapshot": nav_snapshot,
                "nav_post_carry": nav_post_carry,
                "cash": cash,
                "nav": cash + desired * price,
            }
        )
        qty = desired
        previous = timestamp

    return out


def hand_notation(value: float) -> str:
    """Format a number as the .hand.txt writes it.

    Comma-grouped, at the fewest decimals that reproduce the value, capped at the ten places
    used for carry accruals: `6.4438356164` (borrow), `100,149.6537022380` (final NAV),
    `117,600` (a notional), `-626.50` (the dividend). The JSON carries the file's digits, so
    the round trip is exact.
    """
    for places in range(0, 11):
        text = f"{value:,.{places}f}"
        if float(text.replace(",", "")) == value:
            return text
    return f"{value:,.10f}"


def _numbers(node: object, path: str = "") -> list[tuple[str, float]]:
    """Return every numeric leaf in the ledger with its path.

    `index` is skipped: it is an ordinal, and finding "3" in a document full of dates would
    check nothing.
    """
    if isinstance(node, bool) or node is None:
        return []
    if isinstance(node, (int, float)):
        return [(path, float(node))]
    if isinstance(node, dict):
        return [
            pair
            for key, value in node.items()
            if key != "index"
            for pair in _numbers(value, f"{path}.{key}" if path else key)
        ]
    if isinstance(node, list):
        return [pair for i, item in enumerate(node) for pair in _numbers(item, f"{path}[{i}]")]
    return []


# ------------------------------------------------------------- the ledger against itself


def test_the_closed_book_recomputation_reproduces_every_hand_value():
    """Recompute all 19 fields of all 5 bars from the scenario block in stdlib arithmetic.

    This would catch a JSON that was generated by the engine it is meant to check.
    """
    computed = recompute(SCENARIO)
    assert len(computed) == len(BARS)
    for got, want in zip(computed, BARS):
        assert got["timestamp"] == want["timestamp"]
        for field in LEDGER_FIELDS:
            assert field in want, f"bar {want['index']} has no {field!r} in the hand ledger"
            if want[field] is None:
                assert got[field] is None, f"bar {want['index']}: {field} should be null"
                continue
            assert got[field] == pytest.approx(want[field], rel=TOLERANCE, abs=1e-9), (
                f"bar {want['index']}: recomputed {field}={got[field]!r}, "
                f"hand ledger says {want[field]!r}"
            )


def test_the_closed_book_calculator_never_reaches_for_the_engine():
    """`recompute` must not call into the engine.

    It shares a module with the engine's imports, so a disagreement could be "fixed" by
    calling `IBKRCommission().cost(...)`, which would make the golden master check nothing.
    The check reads the source, since such a calculator would behave identically.
    """
    # Code only, with the docstring and comments removed: a prose mention of the package is
    # not a call.
    tree = ast.parse(textwrap.dedent(inspect.getsource(recompute)))
    function = tree.body[0]
    assert isinstance(function, ast.FunctionDef)
    if ast.get_docstring(function) is not None:
        function.body = function.body[1:]
    source = ast.unparse(function)
    # Two complementary checks. The substring check catches dynamic access
    # (`sys.modules["backtest_framework"]`, `importlib.import_module(...)`), which binds
    # nothing at module scope; it cannot see an alias.
    assert "backtest_framework" not in source

    # The resolved-globals check catches aliases such as
    # `from backtest_framework.costs.equity_bricks import IBKRCommission as _c` followed by
    # `_c(...)`: `getclosurevars` returns objects, and an object reports its defining module.
    # A module-level import check is not possible because the other tests here run the engine.
    _assert_resolves_to_no_engine_object(recompute, seen=set())


def _assert_resolves_to_no_engine_object(func, seen: set) -> None:
    """Assert that no global this function uses, directly or via a helper, is from the package.

    Recurses into same-module helpers, since `getclosurevars` does not.
    """
    if func in seen:
        return
    seen.add(func)
    for name, value in inspect.getclosurevars(func).globals.items():
        module = getattr(inspect.getmodule(value), "__name__", "") or getattr(value, "__module__", "") or ""
        assert not module.startswith("backtest_framework"), (
            f"the closed-book calculator uses {name!r}, which resolves to {module}. It must "
            "reproduce the arithmetic without calling the implementation it checks (the check "
            "is on the object, whatever name it is bound to)."
        )
        if inspect.isfunction(value) and inspect.getmodule(value) is inspect.getmodule(func):
            _assert_resolves_to_no_engine_object(value, seen)


def test_every_hand_value_appears_in_the_hand_file():
    """Every number in the JSON appears in the .hand.txt.

    Uses substring containment rather than parsing the prose, which would break on any
    unanticipated sentence. Containment is a weak check (`6.00` contains `6`); the
    recomputation test is the main one. This catches a value added to the JSON that the
    hand derivation never states.
    """
    prose = HAND_TXT.read_text(encoding="utf-8")
    missing = [
        (path, value, hand_notation(value))
        for path, value in _numbers(HAND)
        if hand_notation(value) not in prose
    ]
    assert not missing, (
        f"{len(missing)} value(s) in the hand JSON are not stated in "
        f"{HAND_TXT.name}: {missing[:6]}"
    )
    # Dates: the hand file writes the year once ("Thu 2026-01-08") and the rest month-day
    # ("Fri 01-09"), so the year is checked once and each bar by the form it is written in.
    years = {raw_ts[:4] for raw_ts in SCENARIO["timestamps"]}
    assert len(years) == 1 and years.pop() in prose
    for raw_ts in SCENARIO["timestamps"] + [SCENARIO["dividend"]["ex"]]:
        month_day = raw_ts.split("T")[0][5:]
        assert month_day in prose, f"{month_day} is not a date the hand derivation mentions"


def test_the_hand_file_is_the_transcription_source_and_says_so():
    """The .hand.txt is the source and the JSON is transcribed from it, not the reverse."""
    assert HAND["transcribed_from"] == "tests/golden/test_the_golden_master.hand.txt"
    assert "INDEPENDENT bar-by-bar calculator" in HAND_TXT.read_text(encoding="utf-8")


# ------------------------------------------------------------ the ledger against the engine


def test_every_fill_line_by_line(result):
    expected = [
        (datetime.fromisoformat(b["timestamp"]), SCENARIO["symbol"], b["delta"], b["price"], b["trade_cost"])
        for b in BARS
        if b["delta"] != 0.0
    ]
    assert len(result.fills) == len(expected)
    for actual, exp in zip(result.fills, expected):
        ts, instrument_id, qty, price, cost = actual
        assert (ts, instrument_id) == (exp[0], exp[1])
        assert qty == exp[2]  # share counts are exact integers
        assert price == exp[3]
        assert cost == pytest.approx(exp[4], rel=TOLERANCE)


def test_each_trade_cost_is_its_commission_plus_its_spread(result):
    """Commission and spread are checked separately and must sum to the reported cost.

    `BacktestResult.fills` has one cost number per fill, so $6.00 moved from
    `IBKRCommission` to `PercentOfNotionalSpread` would not change it. The $1 minimum on the
    small re-sizes is the important case, since there commission is not linear in size.
    """
    traded = [b for b in BARS if b["delta"] != 0.0]
    assert len(traded) == len(result.fills)
    for fill, bar in zip(result.fills, traded):
        published = fill[4]
        assert bar["commission"] + bar["spread"] == pytest.approx(published, rel=TOLERANCE), (
            f"bar {bar['index']}: the hand ledger's {bar['commission']} + {bar['spread']} "
            f"is not the {published} the engine reported"
        )
    # The minimum applies on the two small re-sizes, bars 1 and 2, and nowhere else.
    minimum = SCENARIO["commission"]["minimum"]
    by_the_minimum = [
        b for b in traded if b["commission"] == minimum and SCENARIO["commission"]["per_share"] * abs(b["delta"]) < minimum
    ]
    assert [b["index"] for b in by_the_minimum] == [1, 2]


def test_the_cash_curve_carries_the_carry_the_engine_never_reports(result):
    """Borrow, margin interest and the dividend, read from the cash curve.

    The engine records no carry accrual or event flow (see `BacktestResult`), so the carry is
    the part of each bar's cash change that the bar's fill does not explain. Only the sum is
    checked: borrow and margin interest are same-sign deductions at the same instant, and the
    engine reports nothing that separates them.
    """
    cash = [value for _ts, value in result.cash_curve]
    previous = SCENARIO["starting_cash"]
    for bar, actual in zip(BARS, cash):
        # cash_t = cash_{t-1} - borrow - margin + dividend - (delta * price) - trade_cost
        implied_carry = actual - previous + bar["delta"] * bar["price"] + bar["trade_cost"]
        expected_carry = bar["dividend"] - bar["borrow"] - bar["margin_interest"]
        assert implied_carry == pytest.approx(expected_carry, rel=TOLERANCE, abs=1e-6), (
            f"bar {bar['index']}: the cash curve moved by a carry of {implied_carry!r}; "
            f"the hand ledger says borrow {bar['borrow']!r} + margin "
            f"{bar['margin_interest']!r} + dividend {bar['dividend']!r}"
        )
        previous = actual


def test_the_dividend_debit_lands_on_the_right_bar_with_the_right_sign(result):
    """The short pays the dividend: the flow is negative, lands on the ex-date bar only, and
    equals the share count times the per-share amount."""
    ex = datetime.fromisoformat(SCENARIO["dividend"]["ex"])
    on_ex = [b for b in BARS if datetime.fromisoformat(b["timestamp"]) == ex]
    assert len(on_ex) == 1
    bar = on_ex[0]
    assert bar["dividend"] < 0.0, "a short position pays the dividend to the lender"
    assert bar["dividend"] == pytest.approx(
        bar["qty_before"] * SCENARIO["dividend"]["per_share"], rel=TOLERANCE
    )
    assert all(b["dividend"] == 0.0 for b in BARS if b["index"] != bar["index"])
    # It also appears in the engine's cash curve as a step of this size, net of the bar's
    # fill and its two accruals.
    cash_before = SCENARIO["starting_cash"] if bar["index"] == 0 else BARS[bar["index"] - 1]["cash"]
    step = bar["cash"] - cash_before
    assert step == pytest.approx(
        bar["dividend"] - bar["borrow"] - bar["margin_interest"] - bar["delta"] * bar["price"] - bar["trade_cost"],
        rel=TOLERANCE,
    )
    assert result.cash_curve[bar["index"]][1] == pytest.approx(bar["cash"], rel=TOLERANCE)


def test_cash_curve_line_by_line(result):
    expected = [(datetime.fromisoformat(b["timestamp"]), b["cash"]) for b in BARS]
    assert [ts for ts, _ in result.cash_curve] == [ts for ts, _ in expected]
    for (_, actual), (_, exp) in zip(result.cash_curve, expected):
        assert actual == pytest.approx(exp, rel=TOLERANCE)


def test_equity_curve_line_by_line(result):
    expected = [(datetime.fromisoformat(b["timestamp"]), b["nav"]) for b in BARS]
    assert [ts for ts, _ in result.equity_curve] == [ts for ts, _ in expected]
    for (_, actual), (_, exp) in zip(result.equity_curve, expected):
        assert actual == pytest.approx(exp, rel=TOLERANCE)


def test_nav_is_cash_plus_the_marked_position_every_bar(result):
    """NAV equals cash plus the position marked at the close, using the ledger's share count
    rather than the engine's."""
    for bar, (_ts, nav) in zip(BARS, result.equity_curve):
        assert nav == pytest.approx(bar["cash"] + bar["qty_after"] * bar["price"], rel=TOLERANCE)


def test_final_state(result):
    assert result.final_positions.get(SCENARIO["symbol"], 0.0) == 0.0
    assert result.final_nav == pytest.approx(HAND["final_nav"], rel=TOLERANCE)
    # The book ends flat, so NAV == cash. (The P&L decomposition, final NAV - start ==
    # short price P&L - all frictions - dividend debit, is checked in the next test.)
    assert result.final_cash == pytest.approx(result.final_nav, rel=TOLERANCE)


def test_the_frictions_and_the_price_pnl_account_for_the_whole_result():
    """Price P&L minus frictions accounts for the whole change from 100,000 to the final NAV.

    Price P&L on the varying short is +967.00; the five frictions take 817.35 of it, of
    which the dividend is 626.50, 4.5x the commission and spread the engine reports.
    """
    price_pnl = sum(
        bar["qty_after"] * (nxt["price"] - bar["price"]) for bar, nxt in zip(BARS, BARS[1:])
    )
    assert price_pnl == pytest.approx(967.0, abs=1e-9)
    frictions = sum(
        bar["commission"] + bar["spread"] + bar["borrow"] + bar["margin_interest"] - bar["dividend"]
        for bar in BARS
    )
    assert price_pnl - frictions == pytest.approx(
        HAND["final_nav"] - SCENARIO["starting_cash"], rel=TOLERANCE
    )


def test_the_engine_still_publishes_no_per_brick_attribution():
    """`BacktestResult` has no field for commission, spread, borrow, margin interest or flows.

    This is why the decomposition needs a hand ledger. If the engine gains attribution, this
    test fails: delete it and assert the new fields against the ledger component by
    component instead of inferring their sum from the cash curve.
    """
    published = set(BacktestResult.__dataclass_fields__)
    for absent in ("commissions", "spreads", "borrow", "carry", "carry_curve", "flows", "dividends", "attribution"):
        assert absent not in published, (
            f"BacktestResult now publishes {absent!r}. Assert it against the hand ledger "
            "and delete this test; the inference through the cash curve is a workaround."
        )
    assert "fills" in published and "cash_curve" in published and "equity_curve" in published
