"""One-time (manual, NETWORK) fetch of the BINANCE 15m crypto fixture (D190/D191/D193).

The first fixture in this repo written from a provider other than yfinance. Everything
downstream of this script is offline and deterministic, as with every other fetch here.

## Why 15m, and why 1m is not committed

`docs/results/binance_provider_probe.md` measured the archive before this was designed.
Two of its numbers decide the shape of this script:

**Storage.** The reachable universe holds 6.34 GB of compressed 1m archives — 952x the
largest committed fixture and 367x the whole `.git`. So the 1m base is NOT committed. What
is committed is the provider's own SHA256 manifest (D191), which is independently
verifiable and cannot be quietly regenerated by us, plus this derived 15m fixture.

**Empty bars.** The 57.97% empty-minute rate D192 recorded on `BTGUSDT` 2022-01 is a 1m
phenomenon and does not survive aggregation:

      instrument-month        1m      5m     15m      1h
      BTGUSDT 2022-01     57.97%  13.83%   0.97%   0.00%
      XEMUSDT 2022-09     56.68%  10.68%   0.73%   0.00%
      BTCUSDT 2017-09     22.02%   3.34%   0.32%   0.00%

At 15m the worst case is under 1%, so `clean-v1` is not edited, the sanity gate is not
overridden, and D192's and D143's deferrals both stay unspent.

## What is fetched

Two majors and two dead coins. `BTCUSDT`/`ETHUSDT` match D189 exactly, so the S1 terrain
re-test is a clean comparison. `XEMUSDT`/`BTGUSDT` are delisted names carrying the
empty-bar problem this fixture has to prove it handles — the failure universe is the only
screen in this project that ever caught anything (D140/D180), and a path tested only on
majors is a path tested only where it works.

Full available span, untrimmed. The illiquid early years are kept and their empty-bar rate
reported: trimming is a study decision, not a fetch decision, and thin early data is
failure-like data.

## Three columns, none derived from another

Binance states base volume, quote volume and taker-buy volume as separate named fields.
The fixture carries all three (D190's schema extension). `volume` is QUOTE notional — the
convention every crypto fixture here uses, what `CostTier.volume_units` defaults to, and
what D189's S1 sensor ran on. Deriving one from another through price is the D187 defect.

Run: uv run python scripts/fetch_binance_fixture.py
Freeze-only, offline, from the committed fixture:  --freeze-only
"""

from __future__ import annotations

import json
import statistics
import sys
import time
from datetime import date, datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from backtest_framework.data.binance_archive import (  # noqa: E402
    gap_census,
    volume_census,
)
from backtest_framework.data.binance_source import BinanceDataSource  # noqa: E402
from backtest_framework.data.cleaner import clean  # noqa: E402
from backtest_framework.data.corporate_actions import (  # noqa: E402
    CorporateActions,
    load_events_json,
    save_events_json,
)
from backtest_framework.data.csv_fixture import (  # noqa: E402
    load_fixture_csv_with_extras,
    save_fixture_csv,
)
from backtest_framework.data.snapshot_store import SnapshotStore  # noqa: E402
from backtest_framework.data.validator import validate  # noqa: E402
from backtest_framework.research.breakout_intraday import (  # noqa: E402
    Frequency,
    census_days,
    resample,
)

SYMBOLS: tuple[str, ...] = ("BTCUSDT", "ETHUSDT", "XEMUSDT", "BTGUSDT")
"""Two majors matching D189, two delisted names carrying the empty-bar problem."""

SOURCE_INTERVAL = "1m"
TARGET = Frequency("15m", 15)
START, END = date(2017, 1, 1), date(2026, 12, 31)
"""Wider than any symbol's span on purpose — the archive's own listing decides the range,
so this cannot silently truncate a symbol to a hard-coded window."""

FIXTURES = REPO / "data" / "fixtures"
MANIFESTS = REPO / "data" / "manifests"
STEM = "crypto_binance_15m_raw"
OUT = FIXTURES / f"{STEM}.csv.gz"
EVENTS = FIXTURES / f"{STEM}_events.json"
META = FIXTURES / f"{STEM}.meta.json"
MANIFEST = MANIFESTS / "binance_1m_majors.json"


# ---------------------------------------------------------------- fetch


def fetch_one(source: BinanceDataSource, symbol: str) -> dict:
    """Fetch 1m, census the empty bars, drop partial days, resample to 15m."""
    bars, columns, report = source.get_volume_columns(
        symbol, START, END, SOURCE_INTERVAL
    )

    # The D192 census, at the source frequency where the finding actually lives. Measured
    # on the way past, because a rate quoted from the 15m output would understate it by
    # two orders of magnitude and say nothing about the data this was built from.
    #
    # Against the provider's OWN trade count, never a proxy derived from volume: the whole
    # question is whether zero volume agrees with zero trades, and inferring one from the
    # other would make the test answer itself.
    trade_counts = [int(n) for n in columns["trades"]]
    census_1m = volume_census(columns["base_volume"], trade_counts)
    if not census_1m.agrees:
        raise SystemExit(
            f"{symbol}: {census_1m.zero_volume:,} zero-volume 1m bars but "
            f"{census_1m.zero_trades:,} zero-trade bars ({census_1m.zero_volume_and_zero_trades:,} "
            "both) — they DISAGREE, which by D192's criterion is a provider defect and not a "
            "true empty minute. Refusing to build a fixture on it."
        )

    # D161's day-level drop policy, applied for TWO distinct reasons that are counted
    # separately because they are different facts about the provider.
    #
    # 1. Short days. `resample` refuses to emit a bucket missing any of its source bars,
    #    and 1m archives do skip the odd minute.
    # 2. OFF-GRID days. From 2017-12-04 06:00 to 2017-12-18 10:00 every BTCUSDT 1m bar is
    #    stamped 20.799 seconds past the minute — a constant clock skew, not jitter, and
    #    ETHUSDT carries 20.810s over the same fortnight. Those bars cannot be placed on
    #    the grid honestly: the OHLC of a bar labelled 00:00:20.799 could belong to
    #    [00:00, 00:01) or to [00:00:20.8, 00:01:20.8) and the archive does not say which.
    #    Snapping them would be inventing the answer, so the day is dropped and reported
    #    the way clean-v1 drops a bad print rather than correcting it (D25).
    day_census = census_days(bars, source_minutes=1)
    offgrid = report.offgrid
    offgrid_days = set(offgrid.days) if offgrid else set()

    # An off-grid RUN cannot simply be dropped the way an isolated short day can, and the
    # first version of this script got that wrong. Removing 2017-12-04..2017-12-18 made
    # 2017-12-03 and 2017-12-19 adjacent, and the validator correctly called the result a
    # +69.0% single-bar move on BTC and +68.4% on ETH. It was neither a bad print nor a
    # real move: it was fifteen days of the December 2017 rally collapsed into one bar by
    # the drop policy itself.
    #
    # A one-day hole is what the 1h fixture already accepts (D161) and it does not
    # fabricate a material discontinuity. A two-month skew window does. So the series is
    # TRUNCATED to start after the last off-grid day rather than stitched across it, and
    # the cost is reported. Losing real months is the honest price of not manufacturing an
    # adjacency that every downstream return, sigma and channel would silently consume.
    trimmed_days = 0
    if offgrid_days:
        cutoff = max(offgrid_days)
        before = len(day_census.complete)
        keep_days = tuple(
            d for d in day_census.complete if d > cutoff and d not in offgrid_days
        )
        trimmed_days = before - len(keep_days)
    else:
        keep_days = day_census.complete
    if not keep_days:
        raise SystemExit(f"{symbol}: no complete on-grid days survive the drop policy")

    series: dict[str, list[float]] = {}
    out_bars = None
    for name in ("quote_volume", "base_volume", "taker_buy_base"):
        resampled, values, resample_report = resample(
            bars, columns[name], TARGET.minutes, keep_days, source_minutes=1
        )
        resample_report.check()
        series[name] = values
        if out_bars is None:
            out_bars = resampled
        elif [tb.timestamp for tb in resampled] != [tb.timestamp for tb in out_bars]:
            raise SystemExit(
                f"{symbol}: resampling {name} produced a different bar grid than "
                "quote_volume — the three columns would not be index-aligned"
            )
    assert out_bars is not None

    # At 15m a bucket's trade count is the sum of its minutes', so the agreement carries
    # over by construction; the rate is what is being reported here, not the agreement.
    resampled_trades, trade_series, _ = resample(
        bars, columns["trades"], TARGET.minutes, keep_days, source_minutes=1
    )
    census_15m = volume_census(series["base_volume"], [int(n) for n in trade_series])

    print(
        f"  {symbol:<9} {report.bars:>9,} 1m bars -> {len(out_bars):>7,} 15m bars  "
        f"({len(keep_days):,} days kept, {len(day_census.incomplete)} short, "
        f"{trimmed_days} lost to the off-grid truncation)  "
        f"empty 1m {census_1m.zero_volume_rate:>7.3%} -> 15m {census_15m.zero_volume_rate:>6.3%}  "
        f"seam dups {report.seam_duplicates_dropped}"
    )
    if offgrid_days:
        print(
            f"    OFF-GRID: {offgrid.bars:,} bars across {len(offgrid_days)} days "
            f"({offgrid.days[0]} .. {offgrid.days[-1]}), offsets "
            f"{offgrid.residual_seconds}s past the minute — dropped, not snapped"
        )

    return {
        "symbol": symbol,
        "bars": out_bars,
        "series": series,
        "report": report,
        "meta": {
            **report.to_meta(),
            "first_bar": out_bars[0].timestamp.isoformat(),
            "last_bar": out_bars[-1].timestamp.isoformat(),
            "bar_count": len(out_bars),
            "gap_histogram_minutes": gap_census(out_bars, TARGET.minutes),
            "source_bars_1m": report.bars,
            "empty_bars_1m": census_1m.zero_volume,
            "empty_rate_1m": census_1m.zero_volume_rate,
            "zero_trade_bars_1m": census_1m.zero_trades,
            "zero_volume_agrees_with_zero_trades_1m": census_1m.agrees,
            "empty_bars_15m": census_15m.zero_volume,
            "empty_rate_15m": census_15m.zero_volume_rate,
            "days_kept": len(keep_days),
            "days_dropped_short": len(day_census.incomplete),
            "days_dropped_offgrid": len(offgrid_days),
            "days_lost_to_offgrid_truncation": trimmed_days,
            "short_day_detail": [
                [d.isoformat(), n] for d, n in day_census.incomplete[:20]
            ],
            "offgrid": offgrid.to_meta() if offgrid else None,
            "median_quote_volume_15m": statistics.median(series["quote_volume"]),
        },
    }


def write_fixture(results: list[dict], elapsed: float) -> None:
    bars_by_symbol = {r["symbol"]: r["bars"] for r in results}
    volumes_by_symbol = {r["symbol"]: r["series"]["quote_volume"] for r in results}
    extra_columns = {
        "base_volume": {r["symbol"]: r["series"]["base_volume"] for r in results},
        "taker_buy_base": {r["symbol"]: r["series"]["taker_buy_base"] for r in results},
    }
    save_fixture_csv(OUT, bars_by_symbol, volumes_by_symbol, extra_columns)

    # Empty-but-present, and the guard that refuses to write a fixture whose empty events
    # sidecar would be a lie (D48/D108) is kept even though this provider cannot trip it.
    save_events_json(
        EVENTS,
        CorporateActions(
            dividends_by_symbol={s: [] for s in bars_by_symbol},
            splits_by_symbol={s: [] for s in bars_by_symbol},
        ),
    )

    records = [rec.to_json() for r in results for rec in r["report"].records]
    MANIFESTS.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(
        json.dumps(
            {
                "provider": "data.binance.vision",
                "market": "spot",
                "interval": SOURCE_INTERVAL,
                "note": (
                    "SHA256 as PUBLISHED BY THE PROVIDER, not computed by this repo (D191). "
                    "The raw 1m archives are not committed — 6.34 GB for the reachable "
                    "universe. This manifest is the committed record of what they were, and "
                    "it is independently verifiable by anyone who fetches them. An entry "
                    "whose hash changes means the provider rewrote history and must fail the "
                    "fetch, not be merged."
                ),
                "archives": records,
            },
            indent=2,
            sort_keys=True,
        ),
        encoding="utf-8",
    )

    META.write_text(
        json.dumps(
            {
                "symbols": list(bars_by_symbol),
                "start": START.isoformat(),
                "end": END.isoformat(),
                "interval": TARGET.name,
                "minutes_per_bar": TARGET.minutes,
                "bar_boundary": (
                    "UTC, on the 15-minute grid (D161) — timestamps stored naive, meaning UTC"
                ),
                "source": (
                    "Binance public flat-file archives (data.binance.vision), spot monthly 1m "
                    "klines resampled to 15m under D161's contract. TRUE AS-TRADED FRAME: no "
                    "split adjustment, no dividend adjustment, and spot crypto has neither "
                    "event — so as_traded_from_adjusted must NOT be applied (D190)."
                ),
                "volume_columns": {
                    "volume": "quote_volume — USDT notional, the convention every crypto "
                    "fixture here uses and what D189's S1 sensor ran on",
                    "base_volume": "base units (coins), as the provider states them",
                    "taker_buy_base": "base units bought by the aggressor; taker sell volume "
                    "is base_volume - taker_buy_base",
                },
                "manifest": MANIFEST.name,
                "storage_policy": (
                    "1m base NOT committed (D191) — the manifest of provider-published "
                    "SHA256s is the committed record; raw archives cache under data/raw/"
                ),
                "drop_policy": (
                    "D161 day-level: a UTC day the provider did not serve in full is dropped "
                    "entirely, because resample refuses to emit a short bucket"
                ),
                "screen_note": (
                    "apply_policy / DEFAULT_POLICY is deliberately NOT run. Both its volume "
                    "floor (5,000,000 USD) and its peg screen (median |log return| >= 0.5%) "
                    "are per-BAR medians calibrated on DAILY bars; on 15m bars the peg screen "
                    "alone would exclude every symbol in the universe. A daily screen applied "
                    "to intraday bars is not a conservative choice, it is a broken one."
                ),
                "per_symbol": {r["symbol"]: r["meta"] for r in results},
                "fetched_at_utc": datetime.now(timezone.utc).isoformat(),
                "elapsed_seconds": elapsed,
            },
            indent=2,
        ),
        encoding="utf-8",
    )


# ---------------------------------------------------------------- freeze


def freeze() -> tuple[str, dict]:
    """clean -> validate -> snapshot, following `run_breakout_intraday.freeze` (D160).

    `clean` is called on PRICES ONLY. Its `non_positive_volume` rule drops any bar with
    volume at or below zero, and at 15m a genuinely empty bar still happens on a dying
    coin — under 1% of them, but they are TRUE bars. D192 established the criterion:
    zero volume is droppable only where it DISAGREES with the trade count, and here it
    agrees everywhere. Nothing about the shared cleaner is edited; the volume columns are
    written to the snapshot in full and the validator still sees them, so the empty bars
    surface as `zero_volume` WARNINGS in the metadata rather than as a silently shortened
    fixture.

    What the volume rule WOULD have dropped is measured, not assumed, and recorded.
    """
    bars, volumes, extras = load_fixture_csv_with_extras(OUT)
    actions = load_events_json(EVENTS)

    cleaned, price_report = clean(bars)
    for symbol in bars:
        if len(cleaned[symbol]) != len(bars[symbol]):
            raise SystemExit(
                f"{symbol}: price-only cleaning dropped "
                f"{len(bars[symbol]) - len(cleaned[symbol])} bar(s); the volume series would "
                "no longer align with the bars it is validated against"
            )

    _, full_report = clean(bars, volumes)
    validation = validate(cleaned, actions, volumes)

    store = SnapshotStore(REPO / "data" / "snapshots")
    snapshot_id = store.create(
        cleaned,
        actions,
        volumes_by_symbol=volumes,
        cleaning_report=price_report,
        validation=validation,
        extra_columns=extras,
        extra_meta={
            "source_fixture": OUT.name,
            "study": "binance_15m_v1",
            "cleaning_note": "clean() called on prices only — see scripts/fetch_binance_fixture.py",
            "volume_rule_would_have_dropped": len(full_report.changes),
        },
    )
    # No allow_quarantined. The probe measured zero hard violations at 15m on the worst
    # months in the universe, so if this raises the measurement was wrong and the run
    # should stop rather than proceed under an override nobody justified.
    store.load(snapshot_id)

    from collections import Counter

    gate = {
        "snapshot_id": snapshot_id,
        "cleaning_changes": len(price_report.changes),
        "volume_rule_would_have_dropped": len(full_report.changes),
        "hard_violations": len(validation.hard_violations),
        "warnings": len(validation.warnings),
        "warning_by_check": dict(Counter(v.check for v in validation.warnings)),
        "quarantined": not validation.passed,
    }
    return snapshot_id, gate


def report_gate(gate: dict) -> None:
    print(f"snapshot {gate['snapshot_id']} (quarantined={gate['quarantined']})")
    print(
        f"  cleaning changes {gate['cleaning_changes']}, "
        f"hard violations {gate['hard_violations']}, warnings {gate['warnings']:,} "
        f"{gate['warning_by_check']}"
    )
    print(
        f"  the volume rule would have dropped {gate['volume_rule_would_have_dropped']:,} bars "
        "(measured, not assumed — clean() was called twice)"
    )
    if gate["hard_violations"] == 0:
        print(
            "  the gate is SILENT, which is true and uninformative: D74's thresholds are "
            "daily-equity thresholds and a 60% move in 15 minutes is a many-sigma event. "
            "The empty-bar census above is the evidence, not this."
        )


def main() -> int:
    if "--freeze-only" in sys.argv:
        _, gate = freeze()
        report_gate(gate)
        return 0

    started = time.time()
    source = BinanceDataSource()
    print(f"fetching {len(SYMBOLS)} symbols at {SOURCE_INTERVAL} -> {TARGET.name}")

    results: list[dict] = []
    failures: dict[str, str] = {}
    for symbol in SYMBOLS:
        try:
            results.append(fetch_one(source, symbol))
        except Exception as exc:  # noqa: BLE001 — report, never crash the batch
            failures[symbol] = f"{type(exc).__name__}: {exc}"
            print(f"  FETCH FAILED {symbol}: {failures[symbol]}")

    if failures and "--allow-partial" not in sys.argv:
        print(
            f"\n{len(failures)} of {len(SYMBOLS)} symbols failed and no fixture was written. "
            "A fixture missing symbols it claims to hold is worse than no fixture — the "
            "name would not say which ones are absent, and a study loading it would "
            "silently run on a smaller universe. Fix the cause, or pass --allow-partial "
            "if a partial fixture is genuinely what you want.",
            file=sys.stderr,
        )
        for symbol, reason in failures.items():
            print(f"  {symbol}: {reason}", file=sys.stderr)
        return 1

    elapsed = time.time() - started
    write_fixture(results, elapsed)
    print(
        f"requested {len(SYMBOLS)}, fetched {len(results)}, failed {len(failures)}; "
        f"wrote {OUT.name} ({OUT.stat().st_size / 1e6:.2f} MB) + events + meta + "
        f"{MANIFEST.name} in {elapsed:.0f}s"
    )

    _, gate = freeze()
    report_gate(gate)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
