"""D566 -- the joint forward read (spec 6bf82c3, R8): the NG winter spread (ledger #3) on 2024-01-02 -> 2026-09-09,
and the assembled prop book of the admitted MACD arm (#2, its slice spent in D503) plus the spread.

THIS SPENDS THE NG 2024+ SLICE for the withdrawal-season spread and for any book containing it. It refuses
without --principals-word. The MACD arm's forward daily P&L is REGENERATED by D503's frozen code and asserted
equal to data/d503_forward_book.json before use; its verdict is not revisited.

    uv run python scripts/run_d566_joint_forward_read.py --selftest
    uv run python -u scripts/run_d566_joint_forward_read.py --run --principals-word
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import math
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))


def _load(name, fn):
    s = importlib.util.spec_from_file_location(name, REPO / "scripts" / fn)
    m = importlib.util.module_from_spec(s); sys.modules[name] = m; s.loader.exec_module(m)
    return m


R65 = _load("d565", "run_d565_ng_winter_spread.py")       # D565's frozen spread machinery (loads D564/D561/D557/D556/D555)
R64, R61, R56, R55 = R65.R64, R65.R61, R65.R56, R65.R55
R62 = _load("d562", "run_d562_trend_forward_read.py")     # the forward session-calendar loader
D503 = _load("d503", "d503_forward_book.py")              # the MACD arm, frozen: macd_panel, simulate, rotate, hurdle_p

OUT = REPO / "data" / "d566_joint_forward_read.json"
SPEC = "6bf82c3"
FWD_LO, FWD_HI = D503.FWD_LO, D503.FWD_HI
PRIMARY = R55.PRIMARY
NG_PAIRS_B2 = 20
N_DRAWS = 2000
SEED = 566
REQUIRED_OUTPUTS = ["max_drawdown_convention", "reserved_slice_read", "spec", "commit", "strip_sha256", "d503_sha256", "windows",
                    "harness", "audits", "spread", "macd", "book", "nulls", "hurdle_p", "predictions", "promotion", "verdict", "timing"]


def cost_mask(mask, cbp, days):
    """Return-space cost series for a schedule mask: two sides at the first positioned session of a month and two at
    the last (D565's rule), vectorised; equals D565's loop."""
    T = len(mask); mo = np.array([d[:7] for d in days])
    prev_m = np.r_[False, mask[:-1]]; next_m = np.r_[mask[1:], False]
    same_prev = np.r_[False, mo[1:] == mo[:-1]]; same_next = np.r_[mo[:-1] == mo[1:], False]
    opens = mask & ~(prev_m & same_prev); closes = mask & ~(next_m & same_next)
    c = np.where(opens, 2 * cbp, 0.0) + np.where(closes, 2 * cbp, 0.0)
    return np.nan_to_num(c)


def usd_cost_mask(mask, days, side_cost):
    T = len(mask); mo = np.array([d[:7] for d in days])
    prev_m = np.r_[False, mask[:-1]]; next_m = np.r_[mask[1:], False]
    same_prev = np.r_[False, mo[1:] == mo[:-1]]; same_next = np.r_[mo[:-1] == mo[1:], False]
    opens = mask & ~(prev_m & same_prev); closes = mask & ~(next_m & same_next)
    return np.where(opens, 2 * side_cost, 0.0) + np.where(closes, 2 * side_cost, 0.0)


def band(x, obs, rng):
    x = x[np.isfinite(x)]
    p50, p95 = float(np.percentile(x, 50)), float(np.percentile(x, 95))
    bs = np.array([np.percentile(rng.choice(x, len(x)), 95) for _ in range(300)]); se = float(bs.std(ddof=1))
    marg = (obs - p95) / se if se > 0 else float("inf")
    return {"observed": obs, "p05": float(np.percentile(x, 5)), "p50": p50, "p95": p95, "p95_se": se, "margin_se": marg,
            "pct_rank": float((x < obs).mean()), "clears": bool(obs > p95), "unresolved": bool(abs(marg) < 2), "n": int(x.size)}


def hurdle_with_p2(d, label, p2_pass, p2_note):
    h = D503.hurdle_p(d, label); h["P2_pass"] = bool(p2_pass); h["P2_note"] = p2_note
    h["all_six"] = bool(h["P2_pass"] and h["P3a_pass"] and h["P3b_pass"] and h["P5_pass"])
    return h


def run(word, log=print):
    if not word:
        log("REFUSED: --run reads the reserved NG 2024+ slice for the spread and the book; re-run with --principals-word only on the principal's word."); return 2
    t_start = time.time()
    log(f"D566 -- THE JOINT FORWARD READ on the principal's word: NG spread (#3) and the MACD + spread book, {FWD_LO}..{FWD_HI}\n      spec {SPEC} committed BEFORE this runner (R8)")
    # ---- calendar to 2026-09-09 (D562's loader), the NG strip unfiltered ----
    df = R62.load_fixture_forward()
    live_start = R55.live_start_by_rule(df); gfull = R55.build_grids(df, live_start)
    days = gfull["days"]; T = len(days); me = R55.month_ends(days)
    if str(days[-1]) < FWD_HI:
        raise AssertionError(f"calendar ends {days[-1]}")
    strip = pd.read_csv(R56.STRIP, dtype={"root": str, "contract": str, "ref": str}, encoding="utf-8")
    strip = strip[(strip["ref"] <= FWD_HI) & (strip["root"] == R65.ROOT)]
    A, cols = R64.strip_tables(strip, days, [R65.ROOT])[R65.ROOT]
    r1, r2, dP1, dP2, held, pairs = R65.pair_series(A, cols, days, me)
    y = r1 - r2
    mS = R65.season_mask(days, R65.SEASON_MONTHS) & held
    wP = R55.window_mask(days, *PRIMARY); wF = (days >= FWD_LO) & (days <= FWD_HI); wFull = days >= R55.LONG[0]
    x = np.where(mS, -y, 0.0)
    # harness: extending the strip must not move D565's in-sample primary
    art565 = json.loads((REPO / "data" / "d565_ng_winter_spread.json").read_text(encoding="utf-8"))
    sh_is = R55.sharpe(x[wP])
    if abs(sh_is - art565["primary"]["observed"]) > 1e-9:
        raise AssertionError(f"HARNESS: in-sample spread {sh_is:.6f} != D565 artifact {art565['primary']['observed']:.6f}")
    log(f"  calendar {T} sessions to {days[-1]}; forward {int(wF.sum())} sessions; in-sample spread reproduced {sh_is:+.4f}")

    # ---- D565's audits on the extended pair series, proven to raise ----
    audits = {}
    pb = R65.pairs_pandas(strip, days, me); audits["pairs_checked"] = R65.audit_pairs(pairs, pb)
    try:
        R65.audit_pairs(pairs, pb[1:] + pb[:1]); raise RuntimeError("pair audit accepted shifted formations")
    except AssertionError:
        audits["pair_audit_raises_on_shifted_formation"] = True
    both = [p["both_settle_at_end"] for p in pairs if p["t1"] and int(p["hold_month"][5:7]) in R65.SEASON_MONTHS and p["hold_month"] <= FWD_HI[:7]]
    audits["held_contract_share"] = float(np.mean(both))
    if audits["held_contract_share"] < 1.0:
        raise AssertionError("HELD-CONTRACT AUDIT failed on the extended series")
    mS_b = R65.season_mask_pandas(days, R65.SEASON_MONTHS) & held
    audits["lag_mask_sessions"] = R65.audit_mask(mS, mS_b, me)
    bad = mS.copy(); bad[me[[k for k, t in enumerate(me) if t + 1 < T and mS[t + 1] and not mS[t]]]] = True
    try:
        R65.audit_mask(bad, mS_b, me); raise RuntimeError("lag audit accepted a formation-session mask")
    except AssertionError:
        audits["lag_raises_on_formation_session_mask"] = True
    upp = R56.min_size(gfull, gfull["roots"])[0][gfull["roots"].index(R65.ROOT)]
    specs = json.loads(R55.SPECS.read_text(encoding="utf-8"))["MNG"]; tick_usd = specs["tick_usd"]; comm_rt = R55.COMMISSION_RT["micro"]
    pnl_g = np.where(mS, -(dP1 - dP2) * upp, 0.0)
    audits["sign_in_money_session_forward"] = str(days[R65.audit_sign_in_money(np.where(wF, pnl_g, 0.0), dP1, dP2, mS & wF, upp)])
    for label, badp in (("negated", -pnl_g), ("mislagged", np.roll(pnl_g, 1))):
        try:
            R65.audit_sign_in_money(badp, dP1, dP2, mS, upp); raise RuntimeError(f"sign audit accepted a {label} grid")
        except AssertionError:
            audits[f"sign_raises_on_{label}_grid"] = True
    audits["right_quantity_changes"] = R65.audit_right_quantity(mS, days)
    try:
        R65.audit_right_quantity(np.arange(T) % 2 == 0, days); raise RuntimeError("right-quantity accepted a daily grid")
    except AssertionError:
        audits["right_quantity_raises_on_daily_grid"] = True
    log(f"  audits: {audits}")

    # ---- the spread, forward ----
    side_cost = comm_rt / 2.0 + 0.5 * tick_usd
    F1 = np.full(T, np.nan)
    for k, t in enumerate(me):
        end = me[k + 1] if k + 1 < len(me) else T - 1
        if pairs[k]["t1"]:
            j1, _ = R64.choose_nearby(A, cols, t, days[t], energy=True, ffill=R65.FFILL); F1[t + 1:end + 1] = R64.formation_settles(A, t, R65.FFILL)[j1]
    cbp = side_cost / (F1 * upp)
    c_ret = cost_mask(mS, cbp, days); xn = x - c_ret
    cost_usd = usd_cost_mask(mS, days, side_cost); pnl_n = pnl_g - cost_usd
    dF = days[wF]; mF = mS & wF
    mret = R65.monthly_returns(x, days, mF); mret_usd = R65.monthly_returns(pnl_n, days, mF)
    spread = {"gross": R55.stats_block(x[wF], dF, "spread forward"), "net": R55.stats_block(xn[wF], dF, "spread forward net"),
              "positioned_sessions": int(mF.sum()), "sharpe_positioned_days_only": R55.sharpe(x[mF]), "sortino_positioned_days_only": R55.sortino(x[mF]),
              "months": {"n": int(len(mret)), "mean": float(mret.mean()), "median": float(mret.median()), "hit": float((mret > 0).mean()), "worst": float(mret.min()), "best": float(mret.max()),
                         "list": [(str(p), float(v), float(mret_usd[p])) for p, v in mret.items()]},
              "usd": {"gross": R55.stats_block(pnl_g[wF], dF, "MNG pair forward"), "net": R55.stats_block(pnl_n[wF], dF, "MNG pair forward net"),
                      "total_usd": float(pnl_n[wF].sum()), "cost_usd": float(cost_usd[wF].sum()), "sigma_positioned": float(pnl_n[mF].std(ddof=1)),
                      "max_dd_usd": R55.max_drawdown(pnl_n[wF])},
              "pairs": [p for p in pairs if p["t1"] and int(p["hold_month"][5:7]) in R65.SEASON_MONTHS and FWD_LO[:7] <= p["hold_month"] <= FWD_HI[:7]],
              "in_sample_reference": {"gross_sharpe": art565["primary"]["observed"], "net_sharpe": art565["component_line"]["C_a_net_sharpe"], "months_hit": art565["cells"]["spread/season"]["months"]["hit"]}}
    log(f"  spread forward: gross Sh {spread['gross']['sharpe']:+.3f} / So {spread['gross']['sortino']:+.3f} (SE {spread['gross']['se']:.2f})  net {spread['net']['sharpe']:+.3f}  "
        f"months n {spread['months']['n']} mean {spread['months']['mean']*100:+.2f}% median {spread['months']['median']*100:+.2f}% hit {spread['months']['hit']:.2f} worst {spread['months']['worst']*100:+.2f}%  "
        f"$ net {spread['usd']['total_usd']:+,.0f}")

    # ---- the MACD arm, regenerated by D503's frozen code and asserted against its artifact ----
    meta = json.loads(D503.META.read_text(encoding="utf-8")); spec = json.loads(D503.SPECS.read_text(encoding="utf-8"))
    d_all = pd.read_csv(D503.FIX, encoding="utf-8")
    pk = D503.macd_panel(d_all, meta, spec); days_m = pk["days"]
    if str(days_m.min()) < FWD_LO or str(days_m.max()) > FWD_HI:
        raise AssertionError("MACD panel outside the forward window")
    pnl_tk, trips = D503.simulate(pk["O"], pk["C"], pk["AGREE"], pk["first"], D503.M_HOLD, pk["cost"], pk["tick_pts"])
    macd_d = pnl_tk * pk["tick_usd"]
    rows = D503.simulate_trades(pk["O"], pk["C"], pk["AGREE"], pk["first"], D503.M_HOLD, pk["cost"], pk["tick_pts"])
    art503 = json.loads((REPO / "data" / "d503_forward_book.json").read_text(encoding="utf-8")); ref = art503["performance"]["macd"]
    # D503 scored the arm on its UNION calendar with K8 (652 sessions; the MACD is absent on 20). Rebuild that calendar from
    # K8's own trade file and compare on it -- the aggregates must agree there, not on the arm's own 632 sessions.
    k8t = pd.read_csv(D503.K8_TRADES, encoding="utf-8")
    cal503 = np.array(sorted(set(days_m.tolist()) | set(k8t["day"].astype(str).tolist())))
    cal503 = cal503[(cal503 >= FWD_LO) & (cal503 <= FWD_HI)]
    a503 = np.zeros(len(cal503)); a503[[int(np.searchsorted(cal503, d)) for d in days_m]] = macd_d
    sh503 = float(a503.mean() / a503.std(ddof=1) * math.sqrt(D503.TRADING_DAYS))
    for name, got, want in (("mean_usd", float(a503.mean()), ref["mean_usd"]), ("daily_sigma_usd", float(a503.std(ddof=1)), ref["daily_sigma_usd"]),
                            ("sharpe", sh503, ref["sharpe"]), ("n_trades", float(len(rows)), float(ref["n_trades"])), ("n_sessions", float(len(cal503)), float(ref["n_sessions"])),
                            ("total_usd", float(a503.sum()), ref["total_usd"])):
        if abs(got - want) > 1e-6 * max(1.0, abs(want)):
            raise AssertionError(f"MACD REPRODUCTION: {name} {got} != D503 artifact {want}")
    harness = {"spread_in_sample_reproduced": sh_is, "macd_regenerated_equals_d503": True, "macd_mean_usd_d503_calendar": float(a503.mean()), "macd_sigma_usd_d503_calendar": float(a503.std(ddof=1)),
               "macd_sharpe_d503_convention": sh503, "macd_n_trades": len(rows), "macd_sessions_own": int(len(days_m)), "d503_union_sessions": int(len(cal503))}
    macd = {"net": R55.stats_block(macd_d, days_m, "MACD arm forward (D503, spent)"), "verdict_d503": art503["verdicts"]["macd_component"],
            "hurdle_p_d503": art503["hurdle_p"]["macd"], "null_d503": art503["nulls"]["macd_signal_rotation"]}
    log(f"  MACD arm regenerated: mean ${macd_d.mean():+.2f} sigma ${macd_d.std(ddof=1):.2f} Sharpe {sh503:+.4f} trades {len(rows)} -- equals D503's artifact")

    # ---- the union calendar and the book ----
    ng_days = days[wF]; cal = np.array(sorted(set(days_m.tolist()) | set(ng_days.tolist())))
    pos_m = {d: i for i, d in enumerate(cal)}
    idx_m = np.array([pos_m[d] for d in days_m]); idx_ng = np.array([pos_m[d] for d in ng_days])
    a_macd = np.zeros(len(cal)); a_macd[idx_m] = macd_d
    a_ng = np.zeros(len(cal)); a_ng[idx_ng] = pnl_n[wF]
    B1 = a_macd + a_ng; B2 = a_macd + NG_PAIRS_B2 * a_ng
    idxW = {q: R61.worst_days(a_macd, R61.WORST_Q[q]) for q in R61.WORST_Q}
    ov = R61.overlay_stats(a_macd, a_ng, idxW)
    book = {"union_sessions": int(len(cal)), "macd_absent": int(len(cal) - len(days_m)), "ng_absent": int(len(cal) - len(ng_days)),
            "rho_daily_union": float(np.corrcoef(a_macd, a_ng)[0, 1]) if a_ng.std() > 0 else None,
            "rho_daily_ng_positioned": float(np.corrcoef(a_macd[a_ng != 0], a_ng[a_ng != 0])[0, 1]) if (a_ng != 0).sum() > 10 else None,
            "spread_c5_on_macd_worst_days": ov["c5"], "spread_c5_hit": ov["c5_hit"], "dd_ratio_volmatched": ov["dd_ratio"],
            "B1": R55.stats_block(B1, cal, "B1: one MNQ MACD + one MNG pair"), "B2": R55.stats_block(B2, cal, f"B2: one MNQ MACD + {NG_PAIRS_B2} MNG pairs"),
            "macd_alone": R55.stats_block(a_macd, cal, "MACD alone on the union calendar"), "ng_alone_x1": R55.stats_block(a_ng, cal, "spread alone, one pair"),
            "ng_alone_x20": R55.stats_block(NG_PAIRS_B2 * a_ng, cal, "spread alone, 20 pairs"),
            "B1_minus_macd_sharpe": R55.sharpe(B1) - R55.sharpe(a_macd), "B2_minus_macd_sharpe": R55.sharpe(B2) - R55.sharpe(a_macd)}
    log(f"  book: union {len(cal)} sessions; rho {book['rho_daily_union']:+.3f}; MACD alone Sh {R55.sharpe(a_macd):+.3f}; B1 Sh {R55.sharpe(B1):+.3f} / So {R55.sortino(B1):+.3f}; "
        f"B2 Sh {R55.sharpe(B2):+.3f} / So {R55.sortino(B2):+.3f}; spread x20 alone Sh {R55.sharpe(NG_PAIRS_B2*a_ng):+.3f}; c5 on MACD worst days {ov['c5']:+.3f}")

    # ---- nulls ----
    rng = np.random.default_rng(SEED)
    live_idx_full = [np.flatnonzero(held & wFull)]
    mask_full = np.where(wFull, mS, False).astype(float)[None, :]; L_full = int(wFull.sum()); nO = L_full - 1
    ks = np.arange(1, nO + 1); keep = (ks >= R55.NULL_PURGE) & (ks <= L_full - R55.NULL_PURGE)
    for k in R61.GUARD_OFFSETS:
        k = k % nO or 1
        mr = R55.rotate_signs(mask_full, live_idx_full, k)[0] > 0
        a1 = np.where(mr, -y, 0.0)[wF]; a2 = np.array([(-y[t] if mr[t] else 0.0) for t in np.flatnonzero(wF)])
        if not np.array_equal(a1, a2):
            raise AssertionError("exactness guard")
    audits["exactness_guard_offsets"] = len(R61.GUARD_OFFSETS)
    n1 = np.full(nO, np.nan); n1s = np.full(nO, np.nan); nb1 = np.full(nO, np.nan); nb2 = np.full(nO, np.nan)
    t0 = time.time()
    for k in range(1, nO + 1):
        mr = R55.rotate_signs(mask_full, live_idx_full, k)[0] > 0
        xr = np.where(mr, -y, 0.0)[wF]; n1[k - 1] = R55.sharpe(xr); n1s[k - 1] = R55.sortino(xr)
        pr = (np.where(mr, -(dP1 - dP2) * upp, 0.0) - usd_cost_mask(mr, days, side_cost))[wF]
        a_r = np.zeros(len(cal)); a_r[idx_ng] = pr
        nb1[k - 1] = R55.sharpe(a_macd + a_r); nb2[k - 1] = R55.sharpe(a_macd + NG_PAIRS_B2 * a_r)
        if k % 1000 == 0:
            log(f"    placement offset {k}/{nO}  {time.time() - t0:.0f}s")
    keep_idx = np.flatnonzero(keep)
    nulls = {"n1_full_spread": dict(band(n1[keep], spread["gross"]["sharpe"], rng), sortino={"observed": spread["gross"]["sortino"], "p50": float(np.nanpercentile(n1s[keep], 50)), "p95": float(np.nanpercentile(n1s[keep], 95))},
                                    offsets_enumerated=nO, purge_sessions=R55.NULL_PURGE, offsets_after_purge=int(keep.sum())),
             "book_placement_B1": band(nb1[keep], R55.sharpe(B1), rng), "book_placement_B2": band(nb2[keep], R55.sharpe(B2), rng)}
    # joint: MACD signal rotated (D503's method) + spread mask at a random purged offset
    nm = len(days_m); jB1 = np.empty(N_DRAWS); jB2 = np.empty(N_DRAWS); jM = np.empty(N_DRAWS)
    t0 = time.time()
    for i in range(N_DRAWS):
        off = int(rng.integers(1, nm)); sg = D503.rotate(pk["AGREE"], off)
        pn, _ = D503.simulate(pk["O"], pk["C"], sg, pk["first"], D503.M_HOLD, pk["cost"], pk["tick_pts"]); mr_d = pn * pk["tick_usd"]
        a_m = np.zeros(len(cal)); a_m[idx_m] = mr_d
        k = int(ks[keep_idx[rng.integers(0, keep_idx.size)]])
        mr = R55.rotate_signs(mask_full, live_idx_full, k)[0] > 0
        pr = (np.where(mr, -(dP1 - dP2) * upp, 0.0) - usd_cost_mask(mr, days, side_cost))[wF]
        a_r = np.zeros(len(cal)); a_r[idx_ng] = pr
        jM[i] = R55.sharpe(a_m); jB1[i] = R55.sharpe(a_m + a_r); jB2[i] = R55.sharpe(a_m + NG_PAIRS_B2 * a_r)
        if (i + 1) % 500 == 0:
            log(f"    joint draw {i + 1}/{N_DRAWS}  {time.time() - t0:.0f}s")
    nulls["joint_B1"] = band(jB1, R55.sharpe(B1), rng); nulls["joint_B2"] = band(jB2, R55.sharpe(B2), rng); nulls["joint_macd_alone"] = band(jM, R55.sharpe(a_macd), rng)
    # alignment: MACD fixed, the spread's realised forward P&L rotated within the union calendar
    al1 = np.empty(N_DRAWS); al2 = np.empty(N_DRAWS)
    for i in range(N_DRAWS):
        off = int(rng.integers(1, len(cal))); ar = D503.rotate(a_ng, off)
        al1[i] = R55.sharpe(a_macd + ar); al2[i] = R55.sharpe(a_macd + NG_PAIRS_B2 * ar)
    nulls["alignment_B1"] = band(al1, R55.sharpe(B1), rng); nulls["alignment_B2"] = band(al2, R55.sharpe(B2), rng)
    nulls["meta"] = {"joint_draws": N_DRAWS, "seed": SEED, "purge_sessions": R55.NULL_PURGE, "sharpe_convention": "R55.sharpe, 252 periods"}
    for k_, v in nulls.items():
        if k_ != "meta":
            log(f"  null {k_:20s} obs {v['observed']:+.3f}  p50 {v['p50']:+.3f}  p95 {v['p95']:+.3f} (SE {v['p95_se']:.3f})  rank {v['pct_rank']:.3f}  {'CLEARS' if v['clears'] else ''}{' UNRESOLVED' if v['unresolved'] else ''}")

    # ---- hurdle P ----
    p2_note = "a calendar spread held through the month is exposure across every permitted venue's flatten time (Topstep 3:10pm CT, MFFU 4:10pm ET): structural FAIL for any book that holds it"
    hp = {"macd_alone_d503": art503["hurdle_p"]["macd"],
          "spread_x1": hurdle_with_p2(a_ng, "spread, one pair", False, p2_note),
          "spread_x20": hurdle_with_p2(NG_PAIRS_B2 * a_ng, "spread, 20 pairs", False, p2_note),
          "B1": hurdle_with_p2(B1, "B1", False, p2_note), "B2": hurdle_with_p2(B2, "B2", False, p2_note),
          "B1_if_flattenable": hurdle_with_p2(B1, "B1 with P2 waived", True, "hypothetical: a venue that permits holding the spread"),
          "B2_if_flattenable": hurdle_with_p2(B2, "B2 with P2 waived", True, "hypothetical: a venue that permits holding the spread")}
    for k_ in ("B1", "B2"):
        h = hp[k_]; log(f"  hurdle P {k_}: P2 {h['P2_pass']} P3a {h['P3a_breaches_per_year']:.2f}/yr ({h['P3a_pass']}) P3b {h['P3b_life_cost']:.2f} ({h['P3b_pass']}) worst ${h['P3c_worst_day_usd']:,.0f} "
                     f"P4 life {h['P4_expected_life_days']} d P5 {h['P5_best_day_share']:.2f} ({h['P5_pass']}) -> all six {h['all_six']}")

    # ---- predictions and the promotion of #3 ----
    sF, nF = spread["gross"]["sharpe"], spread["net"]["sharpe"]; rank = nulls["n1_full_spread"]["pct_rank"]
    preds = {
        "P-1": {"claim": "spread forward gross Sharpe > 0 (point 0.3-1.0); positioned-month hit >= 0.60", "sharpe": sF, "hit": spread["months"]["hit"],
                "holds": bool(sF > 0 and spread["months"]["hit"] >= 0.60), "in_point_range": bool(0.3 <= sF <= 1.0)},
        "P-2": {"claim": "N1-full rank >= 0.80", "value": rank, "holds": bool(rank >= 0.80)},
        "P-3": {"claim": "worst forward month > -5%", "value": spread["months"]["worst"], "holds": bool(spread["months"]["worst"] > -0.05)},
        "P-4": {"claim": "rho(MACD, spread) daily on the union calendar in [-0.20, +0.20]", "value": book["rho_daily_union"], "holds": bool(book["rho_daily_union"] is not None and -0.2 <= book["rho_daily_union"] <= 0.2)},
        "P-5": {"claim": "B1 net Sharpe within 0.05 of the MACD alone", "value": book["B1_minus_macd_sharpe"], "holds": bool(abs(book["B1_minus_macd_sharpe"]) <= 0.05)},
        "P-6": {"claim": "if both positive: B2 > max(MACD alone, spread x20 alone); point 0.9-1.2", "B2": R55.sharpe(B2), "macd": R55.sharpe(a_macd), "spread_x20": R55.sharpe(NG_PAIRS_B2 * a_ng),
                "applicable": bool(R55.sharpe(a_macd) > 0 and R55.sharpe(a_ng) > 0),
                "holds": bool(R55.sharpe(B2) > max(R55.sharpe(a_macd), R55.sharpe(NG_PAIRS_B2 * a_ng))) if (R55.sharpe(a_macd) > 0 and R55.sharpe(a_ng) > 0) else None,
                "in_point_range": bool(0.9 <= R55.sharpe(B2) <= 1.2)},
        "P-7": {"claim": "P2 fails structurally for B1/B2; P3a fails for B2; P5 passes", "P2_B1": hp["B1"]["P2_pass"], "P3a_B2": hp["B2"]["P3a_pass"], "P5_B2": hp["B2"]["P5_pass"],
                "holds": bool(not hp["B1"]["P2_pass"] and not hp["B2"]["P3a_pass"] and hp["B2"]["P5_pass"])},
        "P-8": {"claim": "promotion rule: FULL if gross > 0, net > 0, rank >= 0.80; REMOVED if net < -0.3 or month mean < 0; else PROVISIONAL"},
        "P-9": {"claim": "falsifiers", "spread_below_n1_p50": bool(sF < nulls["n1_full_spread"]["p50"]), "cotiming_hurts": False},
    }
    preds["P-9"]["cotiming_hurts"] = bool(R55.sharpe(a_macd) > 0 and R55.sharpe(a_ng) > 0 and R55.sharpe(B2) <= max(R55.sharpe(a_macd), R55.sharpe(NG_PAIRS_B2 * a_ng)))
    if nF < -0.3 or spread["months"]["mean"] < 0:
        promotion = "REMOVED"
    elif sF > 0 and nF > 0 and rank >= 0.80:
        promotion = "FULL"
    else:
        promotion = "PROVISIONAL"
    verdict = {"spread_forward": "POSITIVE" if sF > 0 else "NON-POSITIVE", "spread_promotion": promotion,
               "book_B1_all_six": hp["B1"]["all_six"], "book_B2_all_six": hp["B2"]["all_six"], "P2_structural": "FAIL for any book holding the spread"}
    log("\n  predictions: " + ", ".join(f"{k} {'holds' if v.get('holds') else ('n/a' if v.get('holds') is None else 'fails')}" for k, v in preds.items() if k not in ("P-8", "P-9")) + f"; P-9 {preds['P-9']}")
    log(f"  PROMOTION of #3: {promotion}   book B1 all six {hp['B1']['all_six']}   B2 all six {hp['B2']['all_six']}")

    res = {"max_drawdown_convention": {"sign": "negative", "note": "Drawdown LEVELS are NEGATIVE: minimum of (cumulative daily P&L - running peak), in simple-return units for the "
                                       "return-space spread cells and in dollars for the dollar series; the hurdle_p block follows D503's conventions. Not a fraction of a compounded peak (D542).", "record": "D542"},
           "reserved_slice_read": {"record": "D566", "instruction": "the principal, 2026-09-20: 'do the forward slice with nulls, find the combined nulls and combined return and ratios'",
                                   "spent_for": ["the NG withdrawal-season spread and every variant", "any assembled book containing it"], "macd_arm": "its slice was spent in D503; regenerated here as a fixed input"},
           "spec": "D566", "commit": SPEC, "strip_sha256": R55.sha256(R56.STRIP), "d503_sha256": R55.sha256(REPO / "data" / "d503_forward_book.json"),
           "windows": {"forward": [FWD_LO, FWD_HI], "sessions_forward_ng": int(wF.sum()), "in_sample_reference": PRIMARY},
           "harness": harness, "audits": audits, "spread": spread, "macd": macd, "book": book, "nulls": nulls, "hurdle_p": hp,
           "predictions": preds, "promotion": promotion, "verdict": verdict, "timing": {"wall_s": round(time.time() - t_start, 1)}}
    missing = [k for k in REQUIRED_OUTPUTS if k not in res]
    if missing:
        raise AssertionError(f"REQUIRED_OUTPUTS missing: {missing}")
    OUT.write_text(json.dumps(R61._clean(res), indent=1), encoding="utf-8")
    log(f"\n  -> {OUT}   ({res['timing']['wall_s']}s)")
    return 0


def selftest() -> int:
    print("D566 SELF-TEST -- no fixture read, no slice read\n")
    rng = np.random.default_rng(66)
    days = pd.bdate_range("2023-10-02", "2024-06-28").strftime("%Y-%m-%d").to_numpy(); T = len(days)
    mask = np.isin(np.array([int(d[5:7]) for d in days]), R65.SEASON_MONTHS)
    # [1] the vectorised cost equals D565's loop rule
    cbp = np.full(T, 1e-4)
    c_vec = cost_mask(mask, cbp, days)
    c_loop = np.zeros(T); mo = np.array([d[:7] for d in days])
    for t in range(1, T):
        if mask[t] and (not mask[t - 1] or mo[t] != mo[t - 1]):
            c_loop[t] += 2 * cbp[t]
        if mask[t] and (t + 1 >= T or not mask[t + 1] or mo[t + 1] != mo[t]):
            c_loop[t] += 2 * cbp[t]
    if not np.allclose(c_vec, c_loop):
        raise AssertionError("cost vectorisation")
    print("  [1] vectorised schedule cost equals the loop rule (two sides to open a month, two to close)")
    # [2] union-calendar mapping: a component absent on a session contributes zero and the sum is exact
    dm = days[::2]; dn = days[1::3]; cal = np.array(sorted(set(dm) | set(dn))); pos = {d: i for i, d in enumerate(cal)}
    am = np.zeros(len(cal)); am[[pos[d] for d in dm]] = 1.0; an = np.zeros(len(cal)); an[[pos[d] for d in dn]] = 2.0
    if not (am.sum() == len(dm) and an.sum() == 2 * len(dn) and (am + an).sum() == len(dm) + 2 * len(dn)):
        raise AssertionError("union mapping")
    print("  [2] union calendar maps both arms without loss; absent sessions are zeros")
    # [3] the run refuses without the principal's word
    if run(False, log=lambda *a: None) != 2:
        raise AssertionError("did not refuse")
    print("  [3] the runner REFUSES without --principals-word")
    # [4] the hurdle wrapper overrides P2 and computes all_six honestly
    d = rng.normal(5, 100, 600)
    h = hurdle_with_p2(d, "t", False, "note")
    if h["P2_pass"] or h["all_six"]:
        raise AssertionError("P2 override")
    print("  [4] hurdle P wrapper carries the structural P2 verdict into all_six")
    # [5] band: an observed value above every draw clears with rank 1
    b = band(rng.normal(0, 1, 500), 10.0, rng)
    if not (b["clears"] and b["pct_rank"] == 1.0):
        raise AssertionError("band")
    print("  [5] null band reports rank and clearance")
    print("\nSELF-TEST PASSED"); return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("--selftest", action="store_true"); ap.add_argument("--run", action="store_true"); ap.add_argument("--principals-word", action="store_true")
    a = ap.parse_args()
    sys.exit(selftest() if a.selftest else run(a.principals_word))
