"""D282 -- the overnight-only short.
Pre-registered in `docs/decisions/D282-the-overnight-only-short.md`, commit
fcffdde, BEFORE this file was written.

    uv run python scripts/run_overnight_short.py            # the study
    uv run python scripts/run_overnight_short.py --selftest  # synthetic, no fixture
    uv run python scripts/run_overnight_short.py --audit-only  # audits, scores nothing

*** DO NOT RUN THIS AS A STUDY. The record RECOMMENDS AGAINST IT. ***

THE PREMISE THAT MOTIVATED THIS FILE HAD THE SIGN BACKWARDS, and the correction
landed after the file was written and before it was ever run. `--selftest` and
`--audit-only` remain useful; `main()` scoring the 19-cell grid does not. Read
the correction section of the record before running anything here.

ONE CHANGE FROM D281: which PART of the bar is earned.

D280 decomposed the next bar and correlated the R9-lagged `hist_L` against each
half, out of sample from 2018-01-01, cross-sectional Spearman within bar. That
measurement was glossed as "a negative IC is tradeable for a short", WHICH IS
FALSE -- a negative IC means low score goes with HIGH forward return, so the
ascending short shorts the names that RISE.

`scripts/d280_sign_audit.py` settled it in money instead of correlation, by
taking the N LOWEST lagged scores -- exactly what `top_n` selects -- and
reporting what a SHORT of them EARNS against the same bar's cross-sectional
mean. POSITIVE bp = the short makes money. Out of sample, no costs:

    ALL  h  N10  overnight gap  -17.60 bp  t -5.42     intraday  -0.65  t -0.10
    ALL  h  N25  overnight gap  -14.64 bp  t -7.18     intraday  +2.66  t +0.71
    ALL  h  N50  overnight gap  -10.97 bp  t -7.07     intraday  +4.02  t +1.49
    ALL  h/range N25 overnight   -3.44 bp  t -3.12
    QUAL h  N25  overnight gap    -4.66 bp  t -3.81

**The structural claim survives and its sign does not.** The effect IS
concentrated in the overnight window -- every intraday cell is insignificant --
but overnight is where THIS BOOK LOSES HARDEST, 11 to 18 bp a night before
costs. D281 reached the same conclusion from a full scored run: its unfiltered
ascending ranking SUBTRACTS 0.113-0.167 gross Sharpe against a turnover-matched
random control at all three N.

The construction below is unchanged and is the one that was pre-registered:
enter at close(t), exit at open(t+1), no intraday exposure ever, rank ASCENDING.
It is NOT flipped to descending -- that is a post-hoc hypothesis generated by
looking at the result above and needs its own pre-registration.

==========================================================================
THE QUANTITY THIS FILE COMPOUNDS, AND WHY IT IS NOT THE FRAMEWORK'S DEFAULT
==========================================================================
`RP.score` and `RP.pooled_returns` compound `panel.total_log_returns`, which is
a CLOSE-TO-CLOSE return. **AN OVERNIGHT BOOK DOES NOT EARN THAT.** Reusing them
would book a full session of exposure this construction never takes, and every
number in the study would belong to a different strategy. So this file carries
its own scorer, and the quantity it compounds is, at column `t`:

    overnight_total_log[i, t] = log( open[i, t+1] / close[i, t] )
                              + log1p( dividend[i, t+1] / open[i, t+1] )

**Column `t` is THE NIGHT AFTER THE CLOSE OF BAR `t`.** The final column is
identically zero -- there is no next bar. A cell is valid only where the name is
live on BOTH `t` and `t+1` and both prices are finite and positive, and **the
position is forced to zero on every night that cannot be priced**, so no fee is
ever charged for a return that does not exist.

Adjacency is required ON THE GRID, which is stricter than `load_ragged` -- that
diffs a symbol's own bars and so books a return ACROSS an internal provider
hole. A multi-day hole is not an overnight return; those name-nights are dropped
and counted.

The dividend sign is the point of the second term: the price drop is inside the
gap, the position is NEGATIVE, so the short PAYS the dividend. Charging it is
what makes this an honest short rather than a raw-OHLC artefact.

THREE DEFAULTS THAT ARE WRONG HERE AND ARE REPLACED, NOT INHERITED
------------------------------------------------------------------
  turnover   `RP.pooled_returns` charges `|diff(pos)|`, so a name held two
             nights running shows ZERO turnover. It was COVERED AT THE OPEN and
             RE-SHORTED AT THE CLOSE: two round trips, not one. This file
             charges `2 * |pos|` units EVERY night, unconditionally.
  P&L conc.  `C.per_symbol_concentration` reads `panel.total_log_returns`.
             Rewritten here against the overnight grid.
  E-prime    `EP.eff_over_book` correlates `panel.log_returns`. It is used
             UNMODIFIED -- it is the pre-registered estimator -- but fed a SHIM
             PANEL whose `log_returns` IS the overnight grid, so it measures
             co-movement of the thing actually earned. Never
             `RP.effective_instruments(panel, ...)`, which D279 recorded as a
             defect returning 5.44 for every cell.

PERIODS PER YEAR STAYS 252 AND EVERY NIGHT IS A ROUND TRIP
-----------------------------------------------------------
One overnight period per trading day, so the annualisation is unchanged and the
Sharpe is comparable to D256/D279/D281. But turnover is ~252 round trips a year
against ~17 for D279's ~15-day holds, so the same `2c` costs ~25.2%/yr per unit
exposure here against ~1.7% there. D279 and D281 fail on drift with costs barely
mattering; THIS ONE LIVES OR DIES ON COST.

THE PRIMARY STATISTIC IS `mean move per trade` BESIDE `2c`, NOT THE SHARPE
--------------------------------------------------------------------------
D265's condition, in which trade count cancels and hit rate never appears:

    mean move per trade  >=  2c        at 5 bp/side, 2c = 10 bp per night

The pre-registration's linear-normal prior put the move at 4.9 / 4.3 / 3.8 bp at
N = 10 / 25 / 50 -- short of the bar but POSITIVE. The sign audit measured the
same quantity directly at -17.60 / -14.64 / -10.97 bp: **the magnitude is three
to four times larger than the prior and the sign is opposite.** So this book
fails M on DIRECTION, before cost is reached, and `main()` would confirm a
number already known to two significant figures.

Note the one interesting magnitude, and note what it is not: **17.60 bp exceeds
the 10 bp bar**, the first time anything in this programme has -- and it is the
size of a LOSS for the pre-registered direction, produced by a script auditing a
sign error rather than by a pre-registered test. It is NOT a tradeable finding
and this file does not act on it. `breakeven_bps` is reported as D264 reported
it.

THE LOOK-AHEAD GATES, BECAUSE THIS HAS ALREADY FAILED ONCE ON THIS FIXTURE
---------------------------------------------------------------------------
D279's `top_n` ranked with `score[:, t]` and `top25` scored +2.250 Sharpe
unlagged against -0.638 lagged. `C.top_n` now lags internally, but A FIX IN A
DEPENDENCY IS NOT A GUARANTEE IN A CALLER. Three gates, any failure aborting:

  L1  `audit_lag` re-derives the held set from `score[:, t-1]` in a SECOND,
      INDEPENDENT implementation and raises on the first disagreement. It
      deliberately does not call `top_n` -- a check that shares the code it
      checks cannot disagree with it.
  L2  `audit_return_window` recomputes the credited return from the raw
      `Stamped`/`Bar` objects, asserting both endpoint DATES and the value. This
      is what proves the earned quantity is `open(t+1)/close(t)` and not the bar.
  L3  `assert_not_close_to_close` asserts the earned grid is materially
      DIFFERENT from `panel.total_log_returns`. Silently reusing close-to-close
      scoring is the one defect that would be invisible in the output.

Information used to select ends at close(t-1); the earned quantity begins at
close(t). A FULL TRADING SESSION SEPARATES THEM. A book entering at close(t)
could legitimately rank on `hist_L[t]`; this one deliberately does not, prints
what it forgoes, and the pre-registration says using it needs its own record.

HURDLES M, V, C, F and E-prime decide. HURDLE H IS COMPUTED AND CARRIES NO
VERDICT, under R7's corollary as D279 established it on this fixture.

Every constant is D256's and D279's, unvaried: 5 bp/side, borrow 3%/yr, rf 4%,
PPY 252, Impulse 34/9, window 252, seed 0, 300 null draws.

RUNTIME is dominated by 19 books x 300 rotation draws and by `eff_over_book` on
the unranked base; budget an hour and read the progress prints.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import math
import sys
import time
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))


def _load(name, filename):
    spec = importlib.util.spec_from_file_location(name, REPO / "scripts" / filename)
    m = importlib.util.module_from_spec(spec)
    sys.modules[name] = m
    spec.loader.exec_module(m)
    return m


B = _load("d256", "run_book_single_names.py")
C = _load("d279", "run_concentrated_short.py")
TD = _load("d279_turnover", "d279_turnover_decomposition.py")
EP = _load("d279_eprime", "d279_fix_eprime.py")
P1 = _load("d280p1", "d280_forecast_precheck.py")
RP = B.RP

OUT = REPO / "data" / "d282_overnight_summary.json"
N_LEVELS = C.N_LEVELS                       # (10, 25, 50), frozen from D279
N_SIMS, SEED = C.N_SIMS, C.SEED             # 300 draws, seed 0
PPY, RF, BORROW, FEE = C.PPY, C.RF, C.BORROW, C.FEE
TWO_C_BP = 2.0 * FEE                        # the cost bar: 10 bp per night
MIN_OVERLAP = EP.MIN_OVERLAP                # 250 held bars, as D279 fixed it
AUDIT_SAMPLES = 4000


# --------------------------------------------------------------------------
# dividends -- parsed here, and cross-checked against the loader's own arithmetic
# --------------------------------------------------------------------------


def dividend_grids(panel, g, events_path):
    """Cash dividends on their EX-DATE bar, as three aligned grids.

    Both sidecar shapes are handled exactly as `load_ragged` handles them:
    `["2016-11-08T00:00:00", 0.09]` and `{"date": ..., "amount": ...}`. The same
    filters are applied -- on the grid, positive, live, finite close -- because
    the whole point of `dlog_close` is to REPRODUCE the loader so a disagreement
    is a defect rather than a convention difference.

      amt         cash per share, summed where two land on one bar
      dlog_close  log1p(amt/close), accumulated PER ITEM exactly as the loader
                  does -- two dividends on one bar give log1p(a/c)+log1p(b/c),
                  not log1p((a+b)/c), and the cross-check is exact only if this
                  matches
      dlog_open   log1p(amt/open), the term an OVERNIGHT position actually owes,
                  because the position is entered at close(t) and the drop is
                  taken at the open of t+1

    The open denominator is the exact decomposition for the overnight leg:
    total = (open(t+1) + D) / close(t), which factors as the gap times
    (1 + D/open(t+1)). The loader's close denominator is the same quantity for a
    close-to-close bar and differs from this at second order."""
    amt = np.zeros_like(panel.closes)
    dlog_close = np.zeros_like(panel.closes)
    dlog_open = np.zeros_like(panel.closes)
    ev = json.loads(Path(events_path).read_text(encoding="utf-8"))
    payload = ev.get("dividends", ev) if isinstance(ev, dict) else ev
    pos_of = {d: i for i, d in enumerate(panel.dates)}
    idx_of = {s: i for i, s in enumerate(panel.symbols)}
    applied, open_fallback = 0, 0
    for s, items in (payload.items() if isinstance(payload, dict) else []):
        i = idx_of.get(s)
        if i is None:
            continue
        for it in items:
            if isinstance(it, (list, tuple)):
                d, a = str(it[0])[:10], float(it[1])
            else:
                d = str(it.get("date") or it.get("ex_date") or "")[:10]
                a = float(it.get("amount", it.get("dividend", 0.0)) or 0.0)
            t = pos_of.get(d)
            if t is None or a <= 0.0 or not panel.live[i, t] or np.isnan(panel.closes[i, t]):
                continue
            amt[i, t] += a
            dlog_close[i, t] += math.log1p(a / panel.closes[i, t])
            o = g["open"][i, t]
            if np.isfinite(o) and o > 0:
                dlog_open[i, t] += math.log1p(a / o)
            else:
                dlog_open[i, t] += math.log1p(a / panel.closes[i, t])
                open_fallback += 1
            applied += 1
    return amt, dlog_close, dlog_open, applied, open_fallback


def assert_dividends_match_loader(panel, dlog_close, tol=1e-9):
    """The loader's `total - log_returns` IS its own log1p(amt/close) on every
    ex-date bar. Rebuilding it from an independent parse and asserting equality
    is what stops a silently-dropped symbol understating the charge on exactly
    the falling, high-yield names this book holds."""
    loader = panel.total_log_returns - panel.log_returns
    worst = float(np.max(np.abs(loader - dlog_close)))
    if not np.isfinite(worst) or worst > tol:
        raise AssertionError(
            f"dividend parse disagrees with load_ragged by {worst:.3e} -- refusing "
            "to charge a dividend grid the loader does not recognise")
    return worst, int((loader != 0.0).sum())


# --------------------------------------------------------------------------
# the overnight return grid -- the quantity this study compounds
# --------------------------------------------------------------------------


def night_grids(panel, g, dlog_open):
    """`on_log[:, t]` is the night AFTER the close of bar t. See the module
    docstring for the exact quantity; nothing else in this file defines it.

    `on_raw_log` is the same without the dividend charge, kept so the dividend
    drag on the HELD book can be reported in bp rather than assumed."""
    O, Cl = g["open"], g["close"]
    n, T = Cl.shape
    on = np.zeros((n, T))
    on_raw = np.zeros((n, T))
    valid = np.zeros((n, T), dtype=bool)

    adjacent = panel.live[:, :-1] & panel.live[:, 1:]      # STRICTER than the loader
    c0, o1 = Cl[:, :-1], O[:, 1:]
    good = (adjacent & np.isfinite(c0) & np.isfinite(o1) & (c0 > 0) & (o1 > 0))
    gap = np.zeros_like(c0)
    gap[good] = np.log(o1[good] / c0[good])
    on_raw[:, :-1] = gap
    on[:, :-1] = gap + np.where(good, dlog_open[:, 1:], 0.0)
    valid[:, :-1] = good

    if not (np.all(np.isfinite(on)) and np.all(np.isfinite(on_raw))):
        raise AssertionError("non-finite overnight return leaked into the grid")

    # how much the strict-adjacency rule costs, so the choice is auditable
    holed = int((panel.live[:, :-1] & ~adjacent).sum())
    return {
        "on_log": on, "on_raw_log": on_raw, "valid": valid,
        "simple": np.expm1(on), "simple_raw": np.expm1(on_raw),
        "nlive": np.maximum(panel.live.sum(axis=0), 1).astype(float),
        "dropped_nonadjacent": holed,
        "priced_nights": int(valid.sum()),
        "unpriced_live_nights": int((panel.live[:, :-1] & ~good).sum()),
    }


def enforce_tradeable(pos, panel, night, start=0):
    """No exposure outside a symbol's window, and NO EXPOSURE ON A NIGHT THE
    BOOK CANNOT PRICE. The second half is the addition: a fee charged for a
    return that does not exist is a fabricated loss, the mirror of contract
    point 4's fabricated price."""
    out = pos * panel.live * night["valid"]
    out[:, :start] = 0.0
    return out


# --------------------------------------------------------------------------
# the scorer
# --------------------------------------------------------------------------


def overnight_score(panel, pos, night, *, ppy=PPY, rf_annual=RF,
                    borrow_annual=BORROW, start=0, light=False):
    """Score an OVERNIGHT book. Mirrors `RP.score`'s conventions exactly except
    where the construction forbids it -- see the module docstring.

    Kept from `RP.score`, so the numbers are comparable to D256/D279/D281:
      * equal weight over LIVE names, never over `n`
      * `ex = r - long_frac*rf - short_frac*borrow`; rf finances the LONG leg,
        so on a short-only book it is inert and is reported as such
      * one period of borrow per period held, at `expm1(log1p(rate)/ppy)`, which
        for a nightly book is the full annual rate on every night held -- the
        conservative reading, and the right one for a position that is short
        across the settlement

    Replaced, because inheriting it would be wrong:
      * TURNOVER IS `2 * |pos|` EVERY NIGHT. Enter at the close, cover at the
        open: a name held two nights running is two round trips, and
        `|diff(pos)|` would call it zero.
      * `trades` is HELD NAME-NIGHTS. `diff(pos) > 0` counts initiations, which
        on a nightly book undercounts by the mean holding run.
    """
    p = enforce_tradeable(pos, panel, night, start)
    simple, nlive = night["simple"], night["nlive"]

    gross_bar = (p * simple).sum(axis=0) / nlive
    units_bar = (2.0 * np.abs(p)).sum(axis=0) / nlive
    cost_bar = (panel.cost_fraction[:, None] * 2.0 * np.abs(p)).sum(axis=0) / nlive
    r = (gross_bar - cost_bar)[start:]

    lf = float((np.maximum(p, 0.0).sum(axis=0) / nlive)[start:].mean())
    sf = float((np.maximum(-p, 0.0).sum(axis=0) / nlive)[start:].mean())
    rf_p = math.expm1(math.log1p(rf_annual) / ppy)
    bor_p = math.expm1(math.log1p(borrow_annual) / ppy)
    ex = r - lf * rf_p - sf * bor_p
    sd = float(np.std(ex, ddof=1))
    if light:
        return {"excess_sharpe": (float(np.mean(ex)) / sd * math.sqrt(ppy)) if sd > 0 else 0.0,
                "total_return": float(np.cumprod(1.0 + r)[-1] - 1.0)}

    eq = np.cumprod(1.0 + r)
    yrs = len(r) / ppy
    dd = eq / np.maximum.accumulate(eq) - 1.0

    held = p[:, start:] != 0.0
    n_trades = int(held.sum())
    # THE PRIMARY STATISTIC. Signed in the trade's own direction, so a profitable
    # short is POSITIVE. Trade count cancels in `move >= 2c` (D265); this is the
    # left-hand side and `TWO_C_BP` is the right.
    sgn = np.sign(p[:, start:])
    mv = (sgn * simple[:, start:])[held]
    mv_raw = (sgn * night["simple_raw"][:, start:])[held]
    move_bp = float(mv.mean() * 1e4) if n_trades else float("nan")
    move_raw_bp = float(mv_raw.mean() * 1e4) if n_trades else float("nan")

    turn_pooled = float(units_bar[start:].sum())
    paid = float(cost_bar[start:].sum())
    charged_bps = float(np.mean(panel.cost_fraction) * 1e4)
    # THE FEE AT WHICH NET REACHES ZERO, borrow held at its charged rate. Costs
    # enter `ex` linearly through a uniform `cost_fraction`, so this is exact
    # rather than a first-order reading; D264's log form is emitted beside it.
    be = 1e4 * (float(ex.sum()) + paid) / turn_pooled if turn_pooled > 0 else None
    be_log = (1e4 * (1.0 - math.exp(-(float(ex.sum()) + paid) / turn_pooled))
              if turn_pooled > 0 else None)

    pnl = (p[:, start:] * simple[:, start:]).sum(axis=1)
    tot = float(pnl.sum())
    active = (p != 0.0).astype(float)
    entries = int(np.sum(np.diff(active, axis=1, prepend=0.0)[:, start:] > 0.0))

    return {
        "excess_sharpe": (float(np.mean(ex)) / sd * math.sqrt(ppy)) if sd > 0 else 0.0,
        "terminal_multiple": float(eq[-1]),
        "cagr": float(eq[-1] ** (1.0 / yrs) - 1.0) if eq[-1] > 0 else -1.0,
        "total_return": float(eq[-1] - 1.0),
        "vol": float(np.std(r, ddof=1) * math.sqrt(ppy)),
        "max_drawdown": float(dd.min()),
        "worst_bar": float(r.min()),
        "exposure_gross": lf + sf, "exposure_long": lf, "exposure_short": sf,
        "gross_edge_annual": float(np.mean(r)) * ppy,
        # --- the cost bar, D265's form ---
        "mean_move_bp": move_bp,
        "mean_move_bp_raw_gap": move_raw_bp,
        "dividend_drag_bp": (move_raw_bp - move_bp) if n_trades else float("nan"),
        "two_c_bp": TWO_C_BP,
        "move_over_2c": (move_bp / TWO_C_BP) if n_trades else float("nan"),
        "clears_M": bool(n_trades > 0 and move_bp >= TWO_C_BP),
        "breakeven_bps": be, "breakeven_bps_logform": be_log,
        "charged_bps": charged_bps,
        # --- counts. `trades` is HELD NAME-NIGHTS; see the docstring. ---
        "trades": n_trades,
        "entries_diff_based": entries,
        "round_trips_per_name_year": (float(n_trades) / max(int((p[:, start:] != 0).any(axis=1).sum()), 1) / yrs),
        "turnover_units": float((2.0 * np.abs(p[:, start:])).sum()),
        "turnover_units_pooled": turn_pooled,
        "cost_paid_pooled": paid,
        "top_name_share": (float(np.max(pnl) / tot) if tot != 0 else None),
        "rf_is_inert": bool(lf == 0.0),
    }


def overnight_rotation_null(panel, pos, night, *, n_sims, seed, ppy=PPY,
                            rf_annual=RF, borrow_annual=BORROW, start=0):
    """`RP.rotation_null`'s construction against the overnight scorer.

    Rolled WITHIN each symbol's own live window, for the reason `RP` gives:
    rolling across the whole grid places exposure on bars where the name did not
    exist, which the live mask then deletes, silently lowering the null's
    exposure and making the hurdle easier.

    Reseeded from SEED and walking symbols in panel order, so draw `k` uses
    IDENTICAL offsets in every book -- which is what makes the per-draw max
    across books a valid best-of-K floor.

    REPORTED, NOT DECISIVE. R7's corollary; see the pre-registration."""
    rng = np.random.default_rng(seed)
    p0 = enforce_tradeable(pos, panel, night, start)
    windows = [panel.index_of[s] for s in panel.symbols]
    sh, mn = np.empty(n_sims), np.empty(n_sims)
    for k in range(n_sims):
        rot = np.zeros_like(p0)
        for i, (a, b) in enumerate(windows):
            seg = p0[i, a:b + 1]
            if seg.size > 1:
                rot[i, a:b + 1] = np.roll(seg, int(rng.integers(0, seg.size)))
        s = overnight_score(panel, rot, night, ppy=ppy, rf_annual=rf_annual,
                            borrow_annual=borrow_annual, start=start, light=True)
        sh[k], mn[k] = s["excess_sharpe"], s["total_return"]
    return sh, mn


# --------------------------------------------------------------------------
# L1 / L2 / L3 -- the look-ahead and return-window gates
# --------------------------------------------------------------------------


def audit_lag(base, score, n, pos):
    """L1. Re-derive the held set from `score[:, t-1]` and assert it matches.

    Deliberately a SECOND implementation rather than a call into `C.top_n`: the
    point is to disagree with it if it is wrong, and a check that shares the code
    it checks cannot. Returns the number of bars verified; raises on the first
    mismatch."""
    if np.any(base[:, 0] != 0.0):
        raise AssertionError("base column 0 is non-zero; hold_book did not lag")
    checked = 0
    for t in range(1, base.shape[1]):
        q = np.flatnonzero(base[:, t] != 0.0)
        if q.size == 0:
            continue
        if q.size <= n:
            want = q
        else:
            s = score[q, t - 1]                       # EXPLICITLY the prior bar
            s = np.where(np.isfinite(s), s, np.inf)
            want = q[np.argsort(s, kind="stable")[:n]]
        got = np.flatnonzero(pos[:, t] != 0.0)
        if got.size != want.size or not np.array_equal(np.sort(got), np.sort(want)):
            raise AssertionError(
                f"top{n} bar {t}: held set does not match the rank of score[:, t-1]")
        checked += 1
    return checked


def held_rank_pctile(base, score, pos, shift):
    """Mean cross-sectional percentile of the HELD names in the bar's score.

    `shift=1` scores them on `score[:, t-1]`, which is all the book may see;
    `shift=0` on `score[:, t]`. A correctly lagged book sits near the BOTTOM of
    the lagged distribution and nearer the middle of the contemporaneous one.
    The D279 defect inverted exactly that."""
    acc = []
    for t in range(1, base.shape[1]):
        q = np.flatnonzero(base[:, t] != 0.0)
        if q.size < 2:
            continue
        h = np.flatnonzero(pos[:, t] != 0.0)
        if h.size == 0:
            continue
        s = np.where(np.isfinite(score[q, t - shift]), score[q, t - shift], np.inf)
        rank = np.empty(q.size, dtype=float)
        rank[np.argsort(s, kind="stable")] = np.arange(q.size)
        acc.append(rank[np.searchsorted(q, h)] / max(q.size - 1, 1))
    return float(np.concatenate(acc).mean()) if acc else float("nan")


def audit_return_window(panel, cleaned, night, amt, n_samples=AUDIT_SAMPLES, seed=SEED):
    """L2. Recompute the credited return from the RAW bar objects.

    This is the check that proves the earned quantity is the overnight leg. For
    each sampled valid cell it asserts THREE things:

      * `cleaned[sym][k].timestamp` is `panel.dates[t]`      -- the entry bar
      * `cleaned[sym][k+1].timestamp` is `panel.dates[t+1]`  -- the exit bar
      * the value equals `log(bar[k+1].open / bar[k].close)` plus the ex-dividend
        charge at `bar[k+1].open`

    The `k`-th live column of a symbol IS its `k`-th cleaned bar -- `load_ragged`
    writes both from one index vector, and `signals_ragged` already asserts the
    counts agree -- so `searchsorted` maps a grid column to a bar without a
    per-symbol date dict."""
    rng = np.random.default_rng(seed)
    vi, vt = np.nonzero(night["valid"])
    if vi.size == 0:
        raise AssertionError("no valid overnight cells at all")
    take = rng.choice(vi.size, size=int(min(n_samples, vi.size)), replace=False)
    order = np.argsort(vi[take], kind="stable")       # group by symbol, one live-index pass each
    checked, worst, last_i, at = 0, 0.0, -1, None
    for k in take[order]:
        i, t = int(vi[k]), int(vt[k])
        if i != last_i:
            at = np.flatnonzero(panel.live[i])
            last_i = i
        j = int(np.searchsorted(at, t))
        if j + 1 >= at.size or at[j] != t or at[j + 1] != t + 1:
            raise AssertionError(f"{panel.symbols[i]}: valid cell {t} is not two adjacent bars")
        b0, b1 = cleaned[panel.symbols[i]][j], cleaned[panel.symbols[i]][j + 1]
        if b0.timestamp[:10] != panel.dates[t] or b1.timestamp[:10] != panel.dates[t + 1]:
            raise AssertionError(
                f"{panel.symbols[i]}: bar dates {b0.timestamp[:10]}/{b1.timestamp[:10]} "
                f"do not match grid dates {panel.dates[t]}/{panel.dates[t + 1]}")
        want = math.log(b1.bar.open / b0.bar.close)
        a = float(amt[i, t + 1])
        if a > 0:
            want += math.log1p(a / b1.bar.open)
        d = abs(want - float(night["on_log"][i, t]))
        if d > 1e-10:
            raise AssertionError(
                f"{panel.symbols[i]} @ {panel.dates[t]}: credited "
                f"{night['on_log'][i, t]:.10f}, close->next-open is {want:.10f}")
        worst = max(worst, d)
        checked += 1
    return checked, worst


def assert_not_close_to_close(panel, night):
    """L3. The one defect that would be invisible in the output.

    If this file ever reverts to `RP.score`, or if the grid is wired to
    `total_log_returns` by accident, every printed number becomes a
    close-to-close book's and nothing else in the run would say so. Asserted,
    with the correlation and the size ratio printed -- D280 measured the gap at
    51.5% of the body, so a ratio near that is the expected reading."""
    a, b = night["on_log"], panel.total_log_returns
    m = night["valid"] & np.isfinite(b)
    if m.sum() < 1000:
        raise AssertionError("too few comparable cells to verify the earned quantity")
    if np.allclose(a[m], b[m], atol=1e-12):
        raise AssertionError(
            "THE EARNED GRID IS THE CLOSE-TO-CLOSE RETURN. An overnight book does "
            "not earn that; refusing to score.")
    corr = float(np.corrcoef(a[m], b[m])[0, 1])
    ratio = float(np.mean(np.abs(a[m])) / np.mean(np.abs(b[m])))
    return corr, ratio, int(m.sum())


# --------------------------------------------------------------------------
# self-test -- synthetic bars, no fixture, no cell scored
# --------------------------------------------------------------------------


def _synth():
    """A three-name, six-bar panel with prices chosen so every quantity below is
    known by hand. AAA gaps up then down; BBB is flat overnight and moves only
    intraday, so a close-to-close scorer and an overnight one MUST disagree on
    it; CCC pays a dividend on bar 3."""
    dates = ["2020-01-02", "2020-01-03", "2020-01-06", "2020-01-07",
             "2020-01-08", "2020-01-09"]
    px = {  # (open, close) per bar; high/low are padded around them
        "AAA": [(100.0, 100.0), (101.0, 102.0), (103.0, 100.0), (99.0, 101.0),
                (102.0, 104.0), (105.0, 103.0)],
        "BBB": [(50.0, 50.0), (50.0, 52.0), (52.0, 49.0), (49.0, 51.0),
                (51.0, 53.0), (53.0, 50.0)],
        "CCC": [(20.0, 20.0), (20.0, 21.0), (21.0, 22.0), (21.5, 21.0),
                (21.0, 20.5), (20.5, 21.0)],
    }
    symbols = sorted(px)
    n, T = len(symbols), len(dates)
    closes = np.full((n, T), np.nan)
    live = np.zeros((n, T), dtype=bool)
    cleaned, index_of = {}, {}
    for i, s in enumerate(symbols):
        bars = []
        for t, (o, c) in enumerate(px[s]):
            hi, lo = max(o, c) * 1.01, min(o, c) * 0.99
            bars.append(RP.Stamped(dates[t], RP.Bar(o, hi, lo, c, 1e6)))
            closes[i, t] = c
            live[i, t] = True
        cleaned[s] = bars
        index_of[s] = (0, T - 1)
    logr = np.zeros((n, T))
    logr[:, 1:] = np.diff(np.log(closes), axis=1)
    total = logr.copy()
    div_amt = np.zeros((n, T))
    div_amt[symbols.index("CCC"), 3] = 0.50
    total[symbols.index("CCC"), 3] += math.log1p(0.50 / closes[symbols.index("CCC"), 3])
    panel = RP.RaggedPanel(symbols, dates, closes, logr, total,
                           np.full(n, FEE / 1e4), live, index_of)
    return panel, cleaned, div_amt, px


def selftest() -> int:
    """Arithmetic gates on synthetic bars. NO FIXTURE IS READ AND NO CELL IS
    SCORED -- this validates the machinery, it does not spend the study."""
    print("D282 SELF-TEST -- synthetic bars, no fixture, no cell scored\n")
    panel, cleaned, amt, px = _synth()
    g = P1.build_grids(panel, cleaned)
    symbols = panel.symbols

    # the loader cross-check, on a panel where the answer is known
    dlog_close = np.zeros_like(panel.closes)
    dlog_open = np.zeros_like(panel.closes)
    for i in range(len(symbols)):
        for t in range(len(panel.dates)):
            if amt[i, t] > 0:
                dlog_close[i, t] = math.log1p(amt[i, t] / panel.closes[i, t])
                dlog_open[i, t] = math.log1p(amt[i, t] / g["open"][i, t])
    worst, n_div = assert_dividends_match_loader(panel, dlog_close)
    print(f"  [1] dividend parse matches the loader to {worst:.1e} on {n_div} ex-date bars")

    night = night_grids(panel, g, dlog_open)

    # (2) the compounded quantity, on a name with no dividend
    i = symbols.index("AAA")
    want = math.log(px["AAA"][1][0] / px["AAA"][0][1])       # open(t+1)/close(t)
    got = float(night["on_log"][i, 0])
    assert abs(want - got) < 1e-12, (want, got)
    assert abs(float(night["on_log"][i, len(panel.dates) - 1])) == 0.0
    print(f"  [2] on_log[AAA,0] = log(open(1)/close(0)) = {got:+.6f}; last column is zero")

    # (3) BBB is FLAT overnight and moves intraday. A close-to-close scorer would
    #     book its whole move; the overnight scorer must book none of it.
    j = symbols.index("BBB")
    assert abs(float(night["on_log"][j, 1])) < 1e-12
    assert abs(float(panel.total_log_returns[j, 2])) > 0.05
    print(f"  [3] BBB overnight {night['on_log'][j, 1]:+.6f} against close-to-close "
          f"{panel.total_log_returns[j, 2]:+.6f} -- the two scorers disagree, as they must")

    # (4) the SHORT owes the dividend
    k = symbols.index("CCC")
    raw, tot = float(night["on_raw_log"][k, 2]), float(night["on_log"][k, 2])
    assert tot > raw, (raw, tot)
    assert abs((tot - raw) - math.log1p(0.50 / px["CCC"][3][0])) < 1e-12
    print(f"  [4] CCC ex-div night: raw gap {raw:+.6f}, dividend-charged {tot:+.6f} -- "
          f"a short's move is {1e4 * (raw - tot):+.1f} bp WORSE")

    # (5) two sides of cost per held name-night, and the move statistic
    pos = np.zeros_like(panel.closes)
    pos[i, 1] = -1.0
    pos[i, 2] = -1.0                                        # two consecutive nights
    s = overnight_score(panel, pos, night)
    assert s["trades"] == 2, s["trades"]
    assert abs(s["turnover_units"] - 4.0) < 1e-12, s["turnover_units"]
    assert s["entries_diff_based"] == 1                     # exactly what makes diff() wrong here
    hand = -0.5 * (float(night["simple"][i, 1]) + float(night["simple"][i, 2])) * 1e4
    assert abs(s["mean_move_bp"] - hand) < 1e-9, (s["mean_move_bp"], hand)
    print(f"  [5] two consecutive nights -> trades 2, turnover 4.0 units "
          f"(diff-based entries would say {s['entries_diff_based']}); "
          f"mean move {s['mean_move_bp']:+.2f} bp matches by hand")

    # (6) the cost charged is exactly 2 sides x fee per held name-night
    free = type(panel)(**{**vars(panel), "cost_fraction": np.zeros_like(panel.cost_fraction)})
    gs = overnight_score(free, pos, night, rf_annual=0.0, borrow_annual=0.0)
    want_cost = 2.0 * (FEE / 1e4) * 2.0 / float(night["nlive"][0])
    assert abs(s["cost_paid_pooled"] - want_cost) < 1e-12, (s["cost_paid_pooled"], want_cost)
    assert gs["cost_paid_pooled"] == 0.0
    print(f"  [6] cost charged {s['cost_paid_pooled']:.3e} = 2 sides x {FEE:.0f}bp x 2 nights "
          f"/ {night['nlive'][0]:.0f} live; the gross panel charges zero")

    # (7) L1 catches an UNLAGGED selection -- the D279 defect, injected on purpose
    T = len(panel.dates)
    base = np.zeros_like(panel.closes)
    base[:, 1:] = -1.0
    score = np.array([[9.0, 1.0, 5.0, 2.0, 7.0, 3.0],
                      [1.0, 9.0, 2.0, 5.0, 3.0, 7.0],
                      [5.0, 5.0, 9.0, 9.0, 9.0, 9.0]])
    good = C.top_n(base, score, 1)
    assert audit_lag(base, score, 1, good) == T - 1
    bad = np.zeros_like(base)
    for t in range(1, T):                                   # rank on score[:, t] -- look-ahead
        bad[int(np.argmin(score[:, t])), t] = -1.0
    try:
        audit_lag(base, score, 1, bad)
    except AssertionError:
        print("  [7] audit_lag PASSES the lagged book and RAISES on the unlagged one")
    else:
        raise AssertionError("audit_lag failed to catch an unlagged selection")

    # (8) L3 refuses a grid that IS the close-to-close return. The panel is tiled
    #     only to clear the check's own >=1000-cell floor; no value changes.
    tiled = np.tile(panel.total_log_returns, (400, 1))
    wide = RP.RaggedPanel(list(range(tiled.shape[0])), panel.dates, None, None, tiled,
                          None, np.ones(tiled.shape, dtype=bool), {})
    try:
        assert_not_close_to_close(wide, {"on_log": tiled.copy(),
                                         "valid": np.ones(tiled.shape, dtype=bool)})
    except AssertionError as e:
        assert "CLOSE-TO-CLOSE" in str(e), e
        print("  [8] assert_not_close_to_close REFUSES a grid equal to total_log_returns")
    else:
        raise AssertionError("L3 failed to catch a close-to-close grid")

    # and it PASSES the real overnight grid, which is the other half of the check
    c8, r8, n8 = assert_not_close_to_close(
        RP.RaggedPanel(list(range(tiled.shape[0])), panel.dates, None, None, tiled, None,
                       np.ones(tiled.shape, dtype=bool), {}),
        {"on_log": np.tile(night["on_log"], (400, 1)),
         "valid": np.tile(night["valid"], (400, 1))})
    print(f"      and PASSES the real overnight grid: corr {c8:+.4f}, "
          f"size ratio {r8:.1%} over {n8:,} cells")

    print("\n  ALL SELF-TESTS PASSED. No fixture was read and no cell was scored.")
    return 0


# --------------------------------------------------------------------------


def _safe_pos(x):
    """Non-positive or non-finite denominators become NaN, which `top_n` ranks
    last. Same guard D280 used when it measured this arm."""
    return np.where(np.isfinite(x) & (x > 0), x, np.nan)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--selftest", action="store_true",
                    help="synthetic arithmetic gates only; reads no fixture, scores no cell")
    ap.add_argument("--audit-only", action="store_true",
                    help="load the fixture, run L1/L2/L3 and the diagnostics, score nothing")
    ap.add_argument("--sims", type=int, default=N_SIMS)
    args = ap.parse_args()
    if args.selftest:
        return selftest()

    t0 = time.time()
    panel, cleaned = RP.load_ragged(B.FIXTURE, B.EVENTS, fee_bps=FEE)
    n, T = panel.closes.shape
    md, hs, g_lo, g_hi, i_lo, atr, warm = B.signals_ragged(panel, cleaned, 0)
    g = P1.build_grids(panel, cleaned)
    print(f"loaded + signals {time.time() - t0:.0f}s   {n} names x {T:,} bars", flush=True)

    # ---- the earned quantity, and the dividend charge on the short leg ----
    amt, dlc, dlo, n_div, fb = dividend_grids(panel, g, B.EVENTS)
    worst, loader_cells = assert_dividends_match_loader(panel, dlc)
    night = night_grids(panel, g, dlo)
    print(f"  dividends: {n_div:,} applied, parse matches the loader to {worst:.1e} "
          f"on {loader_cells:,} ex-date bars ({fb} open fallbacks)")
    print(f"  overnight grid: {night['priced_nights']:,} priced nights, "
          f"{night['dropped_nonadjacent']:,} dropped for non-adjacency (provider holes), "
          f"{night['unpriced_live_nights']:,} live nights unpriced in total", flush=True)

    # the split-adjustment sanity check -- the open must carry the same factor as
    # the close, or a split injects a fabricated gap on exactly one night
    flat = night["on_log"][night["valid"]]
    big = np.sort(np.abs(flat))[-25:][::-1]
    print(f"  largest 25 |overnight| moves (split-adjustment check): "
          + ", ".join(f"{x:.2f}" for x in big[:10]) + " ...", flush=True)

    # ---- L3 first: nothing else matters if the wrong quantity is being earned ----
    corr_cc, ratio_cc, cells_cc = assert_not_close_to_close(panel, night)
    print(f"\n  L3  earned grid vs close-to-close: corr {corr_cc:+.4f}, "
          f"mean |overnight| is {ratio_cc:.1%} of mean |close-to-close| "
          f"over {cells_cc:,} cells   (D280 measured the gap at 51.5% of the body)",
          flush=True)

    # ---- L2: the return window, re-derived from the raw bars ----
    n_checked, worst_d = audit_return_window(panel, cleaned, night, amt)
    print(f"  L2  {n_checked:,} held-night samples re-derived from the raw Bar objects: "
          f"entry date, exit date and value all match (worst {worst_d:.1e})", flush=True)

    # ---- the universe and the two declared ranking arms ----
    ok = ~(np.isnan(md) | np.isnan(hs)) & warm
    base = -B.hold_book(ok, warm)
    rng_frac = (g["high"] - g["low"]) / g["close"]
    # PASSED UNLAGGED because `top_n` lags internally; lag and division commute,
    # so this is exactly D280's `h / safe(rng_l)` -- the arm measured at IC -0.01625.
    arms = {"hist_L": hs, "hist_L_over_range": hs / _safe_pos(rng_frac)}
    print(f"\n  universe: {int((base != 0).sum()):,} name-nights before the "
          f"unpriced-night mask", flush=True)

    rng = np.random.default_rng(SEED)
    books = {"base|all": base}
    for arm, sc in arms.items():
        for N in N_LEVELS:
            books[f"{arm}|top{N}"] = C.top_n(base, sc, N)
            books[f"{arm}|rnd{N}"] = C.top_n(base, sc, N, rng=rng)
            books[f"{arm}|per{N}"] = TD.persistent_rnd(base, N, rng)
    K = len(books)
    print(f"built {K} books {time.time() - t0:.0f}s", flush=True)

    # ---- L1: the R9 gate. Nothing downstream runs until it passes. ----
    print("\n  L1  LAG AUDIT -- the check D279 failed:", flush=True)
    cc = np.expm1(panel.total_log_returns)
    m = panel.live & np.isfinite(hs) & np.isfinite(C.lag1(hs))
    m_on = m & night["valid"]
    audit = {
        "corr_score_lag1_overnight_t": float(np.corrcoef(C.lag1(hs)[m_on], night["simple"][m_on])[0, 1]),
        "corr_score_t_overnight_t": float(np.corrcoef(hs[m_on], night["simple"][m_on])[0, 1]),
        "corr_score_t_closeclose_t": float(np.corrcoef(hs[m & np.isfinite(cc)],
                                                       cc[m & np.isfinite(cc)])[0, 1]),
        "L3_corr_overnight_vs_closeclose": corr_cc,
        "L3_overnight_size_ratio": ratio_cc,
        "L2_samples_verified": n_checked, "L2_worst_abs_error": worst_d,
        "dividends_applied": n_div, "dividend_parse_max_abs_error": worst,
    }
    print(f"      corr(hist_L[t-1], overnight[t]) : {audit['corr_score_lag1_overnight_t']:+.4f}"
          "   <-- WHAT THIS BOOK TRADES")
    print(f"      corr(hist_L[t],   overnight[t]) : {audit['corr_score_t_overnight_t']:+.4f}"
          "   <-- legitimate for an overnight entry, DELIBERATELY UNUSED")
    print(f"      corr(hist_L[t],   close-close[t]): {audit['corr_score_t_closeclose_t']:+.4f}"
          "   <-- D279's contaminated quantity, for reference", flush=True)
    for arm, sc in arms.items():
        for N in N_LEVELS:
            p = books[f"{arm}|top{N}"]
            bars = audit_lag(base, sc, N, p)
            pl, pn = held_rank_pctile(base, sc, p, 1), held_rank_pctile(base, sc, p, 0)
            audit[f"{arm}|top{N}"] = {"bars_verified": bars, "mean_pctile_lagged": pl,
                                      "mean_pctile_contemporaneous": pn}
            print(f"      {arm}|top{N:<3d} {bars:,} bars re-derived from score[:, t-1] and "
                  f"MATCHED; held names sit at pctile {pl:.4f} of the LAGGED score, "
                  f"{pn:.4f} of the contemporaneous one", flush=True)
    print(f"  ALL THREE GATES PASSED {time.time() - t0:.0f}s", flush=True)

    if args.audit_only:
        print("\n  --audit-only: no cell scored, nothing written.")
        return 0

    # ---- NET and GROSS ----
    free = type(panel)(**{**vars(panel),
                          "cost_fraction": np.zeros_like(panel.cost_fraction)})
    net = {k: overnight_score(panel, p, night) for k, p in books.items()}
    gro = {k: overnight_score(free, p, night, rf_annual=0.0, borrow_annual=0.0)
           for k, p in books.items()}
    print(f"\nscored {time.time() - t0:.0f}s\n", flush=True)

    # ---- THE PRIMARY TABLE. This number decides the study, not the Sharpe. ----
    print(f"  HURDLE M -- mean move per trade against 2c = {TWO_C_BP:.1f} bp/night.")
    print("  D265: in this form the trade count cancels and the hit rate never appears.\n")
    print(f"  {'cell':26s} {'move bp':>9s} {'raw gap':>9s} {'div drag':>9s} "
          f"{'x 2c':>7s} {'breakeven':>10s} {'trades':>10s}  M")
    for k in books:
        a = net[k]
        print(f"  {k:26s} {a['mean_move_bp']:+9.3f} {a['mean_move_bp_raw_gap']:+9.3f} "
              f"{a['dividend_drag_bp']:+9.3f} {a['move_over_2c']:7.2f} "
              + (f"{a['breakeven_bps']:9.3f}b" if a['breakeven_bps'] is not None else "         —")
              + f" {a['trades']:10,d}  {'YES' if a['clears_M'] else 'no'}", flush=True)

    print(f"\n  {'cell':26s} {'expo':>7s} {'turnover':>11s} {'net CAGR':>9s} {'net SR':>8s} "
          f"{'GROSS CAGR':>11s} {'GROSS SR':>9s} {'maxDD':>8s}")
    for k in books:
        a, gg = net[k], gro[k]
        print(f"  {k:26s} {a['exposure_gross']:6.2%} {a['turnover_units']:11,.0f} "
              f"{a['cagr']:+8.2%} {a['excess_sharpe']:+8.3f} {gg['cagr']:+10.2%} "
              f"{gg['excess_sharpe']:+9.3f} {a['max_drawdown']:7.2%}", flush=True)

    # ---- E-prime OVER THE HELD BOOK, on the OVERNIGHT return grid ----
    # The shim panel is the whole point: `eff_over_book` is used unmodified, but
    # correlating close-to-close returns for a book that never holds a session
    # would measure a dependence this construction is not exposed to.
    shim = type(panel)(**{**vars(panel), "log_returns": night["on_log"]})
    print(f"\n  E-prime over the HELD BOOK, on the OVERNIGHT grid "
          f"{time.time() - t0:.0f}s ...", flush=True)
    eff = {}
    for k, p in books.items():
        e, kept = EP.eff_over_book(shim, enforce_tradeable(p, panel, night))
        eff[k] = {"eff_book": e, "names_over_min_overlap": kept}
        print(f"    {k:26s} names>={MIN_OVERLAP} held {kept:5d}   E-prime {e:8.2f}   "
              f"{time.time() - t0:.0f}s", flush=True)

    # ---- Rotation nulls. REPORTED, NOT DECISIVE (R7 corollary). ----
    print(f"\n  rotation nulls, {args.sims} draws each -- REPORTED, NOT DECISIVE "
          f"(R7 corollary; D279 established H is broken on this fixture) ...", flush=True)
    cells, draws = {}, []
    for k, p in books.items():
        sh, mn = overnight_rotation_null(panel, p, night, n_sims=args.sims, seed=SEED)
        c = dict(net[k])
        c["gross"] = gro[k]
        c.update(eff[k])
        c["sharpe_pct"] = float((sh < net[k]["excess_sharpe"]).mean() * 100)
        c["money_pct"] = float((mn < net[k]["total_return"]).mean() * 100)
        c["null_sharpe_p50"] = float(np.percentile(sh, 50))
        c["null_sharpe_p95"] = float(np.percentile(sh, 95))
        c["H"] = bool(c["sharpe_pct"] >= 95 and c["money_pct"] >= 95)
        c["V"] = bool(c["cagr"] > 0)
        c["M"] = bool(c["clears_M"])
        c["breakeven_borrow"] = C.breakeven_borrow(panel, p, 0, net[k])
        cells[k] = c
        draws.append(sh)
        print(f"    {k:26s} {c['sharpe_pct']:5.1f}th / {c['money_pct']:5.1f}th   "
              f"null p50 {c['null_sharpe_p50']:+.3f} p95 {c['null_sharpe_p95']:+.3f}   "
              f"{time.time() - t0:.0f}s", flush=True)
    floor = float(np.percentile(np.max(np.vstack(draws), axis=0), 95))
    print(f"\n  best-of-{K} floor: {floor:+.3f}\n", flush=True)

    # ---- The decomposition: what the RANKING is worth against each control ----
    print("  RANKING CONTRIBUTION -- top-N minus each control, gross and net.")
    print("  Every night is a round trip for EVERY book, so rnd-N's fee")
    print("  disadvantage should VANISH: a turnover ratio far from 1.0x")
    print("  falsifies this runner's cost model, not the market.\n")
    print(f"  {'arm':20s} {'N':>4s}  {'vs rnd net':>11s} {'vs rnd GROSS':>13s} "
          f"{'vs per net':>11s} {'vs per GROSS':>13s}   turnover ratio")
    decomp = {}
    for arm in arms:
        for N in N_LEVELS:
            t_, r_, p_ = (net[f"{arm}|{m}{N}"] for m in ("top", "rnd", "per"))
            tg, rg, pg = (gro[f"{arm}|{m}{N}"] for m in ("top", "rnd", "per"))
            d = {"vs_rnd_net": t_["excess_sharpe"] - r_["excess_sharpe"],
                 "vs_rnd_gross": tg["excess_sharpe"] - rg["excess_sharpe"],
                 "vs_per_net": t_["excess_sharpe"] - p_["excess_sharpe"],
                 "vs_per_gross": tg["excess_sharpe"] - pg["excess_sharpe"],
                 "move_bp_top": t_["mean_move_bp"], "move_bp_rnd": r_["mean_move_bp"],
                 "move_bp_per": p_["mean_move_bp"],
                 "turnover_ratio_rnd": r_["turnover_units"] / max(t_["turnover_units"], 1e-9),
                 "turnover_ratio_per": p_["turnover_units"] / max(t_["turnover_units"], 1e-9)}
            decomp[f"{arm}|{N}"] = d
            print(f"  {arm:20s} {N:4d}  {d['vs_rnd_net']:+11.3f} {d['vs_rnd_gross']:+13.3f} "
                  f"{d['vs_per_net']:+11.3f} {d['vs_per_gross']:+13.3f}   "
                  f"rnd {d['turnover_ratio_rnd']:.2f}x per {d['turnover_ratio_per']:.2f}x")

    # ---- Hurdles. C needs EIGHT legs and every one is stored. ----
    print(f"\n  {'cell':26s} {'move bp':>9s} {'net CAGR':>9s} {'GROSS SR':>9s} "
          f"{'M':>3s} {'V':>3s} {'C':>3s} {'F':>3s} {'E-prime':>8s} {'(H)':>5s}  ALL")
    surv = []
    for k in books:
        c = cells[k]
        mode = k.split("|")[1]
        if mode.startswith("top"):
            arm, N = k.split("|")[0], mode[3:]
            legs = {}
            for m in ("rnd", "per"):
                o, og = net[f"{arm}|{m}{N}"], gro[f"{arm}|{m}{N}"]
                legs[f"{m}_sharpe_net"] = c["excess_sharpe"] > o["excess_sharpe"]
                legs[f"{m}_money_net"] = c["total_return"] > o["total_return"]
                legs[f"{m}_sharpe_gross"] = gro[k]["excess_sharpe"] > og["excess_sharpe"]
                legs[f"{m}_money_gross"] = gro[k]["total_return"] > og["total_return"]
            c["C_legs"] = {a: bool(b) for a, b in legs.items()}
            c["C"] = bool(all(legs.values()))
        else:
            c["C_legs"], c["C"] = {}, False
        c["F"] = bool(c["excess_sharpe"] > floor)
        c["Eprime"] = bool(c["eff_book"] >= 3.0 and c["trades"] >= 500)
        # H IS EXCLUDED FROM `clears_all` BY PRE-REGISTRATION. Computed, printed,
        # carrying no verdict -- R7's corollary, established by D279.
        c["clears_all"] = bool(c["M"] and c["V"] and c["C"] and c["F"] and c["Eprime"])
        if c["clears_all"]:
            surv.append(k)
        y = lambda b: "YES" if b else "no"  # noqa: E731
        print(f"  {k:26s} {c['mean_move_bp']:+9.3f} {c['cagr']:+8.2%} "
              f"{gro[k]['excess_sharpe']:+9.3f} {y(c['M']):>3s} {y(c['V']):>3s} "
              f"{y(c['C']):>3s} {y(c['F']):>3s} {y(c['Eprime']):>8s} {y(c['H']):>5s}  "
              f"{'** YES **' if c['clears_all'] else 'no'}")

    print(f"\n  SURVIVORS: {surv or 'NONE'}")
    json.dump({"study": "D282", "seed": SEED, "n_sims": args.sims, "fee_bps": FEE,
               "two_c_bp": TWO_C_BP, "borrow_charged": BORROW, "rf": RF, "ppy": PPY,
               "n_levels": list(N_LEVELS), "arms": list(arms), "floor": floor, "K": K,
               "earned_quantity": ("log(open(t+1)/close(t)) + log1p(div(t+1)/open(t+1)) "
                                   "at column t -- the NIGHT AFTER the close of bar t; "
                                   "2 x |pos| turnover units charged every night"),
               "hurdle_H": "computed, reported, EXCLUDED from every verdict (R7 corollary)",
               "grid": {kk: night[kk] for kk in
                        ("dropped_nonadjacent", "priced_nights", "unpriced_live_nights")},
               "audit": audit, "decomposition": decomp,
               "cells": cells, "survivors": surv,
               "elapsed_s": round(time.time() - t0, 1)},
              open(OUT, "w"), indent=1)
    print(f"\nwrote {OUT.relative_to(REPO)}   {time.time() - t0:.0f}s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
