"""Every decision number on disk appears in `docs/decisions/README.md`.

**This test exists because the index silently stopped being true for 251 numbers.** It was a
curated table of D1–D284; the directory kept growing to D537, and nothing noticed — not a test,
not a script, nothing read the file programmatically at all. Two other documents went stale
alongside it, each telling a contributor to take the next decision number from a table that had
not moved in months: `docs/RULES.md` said D283, the index itself said D280.

The register half is generated by `scripts/build_decision_register.py`. This is what makes the
generation load-bearing rather than a one-off tidy-up: add a record without regenerating and the
suite goes red.

It deliberately asserts **coverage, not format**. The curated half is inconsistent by nature —
17 of its rows carry two cells, 8 carry five to eight because prose contains unescaped `|` — and
a format assertion would either fail on the existing table or force a rewrite of 290 hand-written
summaries nobody asked for.
"""

from __future__ import annotations

import functools
import importlib.util
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DECISIONS = REPO / "docs" / "decisions"


@functools.lru_cache(maxsize=1)
def _register():
    """The generator this gate checks, imported so the two cannot drift apart again (D544)."""
    spec = importlib.util.spec_from_file_location(
        "build_decision_register", REPO / "scripts" / "build_decision_register.py"
    )
    module = importlib.util.module_from_spec(spec)
    sys.modules["build_decision_register"] = module
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module
INDEX = DECISIONS / "README.md"

#: `D<n>-` or `D<n>.` at the START of the basename, an optional single-letter variant suffix
#: (`D315a-RESULT-...`), zero-padding tolerated. The anchor matters: unanchored, `D\d+` finds
#: `D304` inside `D300-AMENDMENT-cost-basis-and-what-D304-and-D305-changed.md` and invents a
#: record. The convention is recorded in `ANCHOR THE PATTERN`
#: (`scripts/build_readme_counts.py:38-43`) and `tests/unit/test_cited_decisions_exist.py`.
#:
#: IMPORTED, NOT RESTATED (D544). This file and its own generator carried two different patterns
#: while the docstring below claimed they had been put back on one universe -- see
#: `RECORD` in `scripts/build_decision_register.py` for what that cost.
RECORD = _register().RECORD


def _numbers_in_the_index_of_record() -> set[int]:
    """The records `git ls-files` knows about — not the ones this worktree happens to hold.

    THE INDEX, NOT THE FILESYSTEM. This globbed the disk, alone among the decision gates, while
    `scripts/build_readme_counts.py`, `scripts/check_doc_links.py` and
    `tests/unit/test_cited_decisions_exist.py` all argue the opposite boundary at length and for
    the same reason: the filesystem counts scratch files nobody else has and misses records
    everyone else has but this worktree deleted.

    Both directions were live here. An untracked scratch record reddened the suite on a state no
    clone shares — and worse, a record staged for deletion mid-renumbering was absent from the
    glob and present in the index, so this gate reported a phantom row for a record a clone
    resolves fine. That is the ordinary state of this repository: two such records are in flight
    right now. It also put this test and `scripts/build_decision_register.py`, which generates the
    half of the index being checked, on different universes — so the gate could disagree with its
    own generator and neither would be wrong.

    `build_readme_counts.py:34-36` records the one deliberate filesystem exception, for
    `test_results_docs_at_root.py`, with its reason: that test hunts files a runner regenerated
    and left untracked, which are invisible to the index. Decision records are authored and
    committed, never regenerated, so the exception does not transfer.
    """
    out = subprocess.run(
        ["git", "ls-files", "docs/decisions/D*.md"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    names = [Path(line).name for line in out.splitlines() if line]
    assert names, (
        "git ls-files matched no decision records — the index is empty or the pathspec is wrong. "
        "Refusing to report a complete index from zero records."
    )
    return {int(m.group(1)) for name in names if (m := RECORD.match(name))}


def _numbers_in_index() -> set[int]:
    # Matches both halves: curated rows `| [D01](…)` and register rows `| D537 | … |`.
    return {int(n) for n in re.findall(r"\|\s*\[?D0*(\d+)", INDEX.read_text(encoding="utf-8"))}


def test_every_decision_number_is_listed_in_the_index():
    missing = sorted(_numbers_in_the_index_of_record() - _numbers_in_index())
    shown = f"{missing[:20]}{' …' if len(missing) > 20 else ''}"
    assert not missing, (
        f"{len(missing)} decision number(s) are not in docs/decisions/README.md: {shown}. "
        "Regenerate the register: `python scripts/build_decision_register.py --write`."
    )


def test_the_index_does_not_list_numbers_that_do_not_exist():
    """The other direction — a row pointing at a record that was deleted or renamed.

    `scripts/check_doc_links.py` catches a broken *link*; this catches a row whose number has no
    file at all, which is the shape a renumbering would leave behind.
    """
    phantom = sorted(_numbers_in_index() - _numbers_in_the_index_of_record())
    assert not phantom, f"index lists decision numbers with no record on disk: {phantom}"


def test_this_gate_and_its_generator_are_on_one_universe():
    """The docstring above claims it; until D544 it was not true.

    This file matched `^D0*(\\d+)[-.]` and `scripts/build_decision_register.py` matched an
    unanchored `D\\d+`. `D315a-RESULT-the-corner-is-real-the-formula-is-not.md` therefore satisfied
    the generator and not the gate: it is **rendered into the index** at `docs/decisions/README.md`
    and was **invisible here**. Harmless only by luck — a plain `D315-` sibling independently put
    315 in the record set. A `D<n>a-` record with no sibling would have been generated into the
    register and then flagged as a phantom by the test directly above this one, i.e. the gate would
    have failed on its own generator's correct output.

    So the pattern is now imported rather than restated, and this asserts the property the prose
    asserts: both classify every tracked basename identically, and the variant form is a record.
    """
    listed = subprocess.run(
        ["git", "ls-files", "docs/decisions/*.md"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split()
    basenames = [Path(p).name for p in listed]
    assert len(basenames) > 700, "the scan lost its input rather than the repo losing records"

    assert RECORD is _register().RECORD, "the gate restated the pattern instead of importing it"

    # The variant form is a record to both, and the unanchored trap is a record to neither.
    assert RECORD.match("D315a-RESULT-the-corner-is-real-the-formula-is-not.md")
    assert RECORD.match("D315-below-the-corner-and-the-derived-rule.md")
    assert not RECORD.match("DRAFT-capturing-the-deeper-zone.md")
    assert not RECORD.match("README.md")
    # Anchored: the embedded D304 must not invent a record.
    embedded = "D300-AMENDMENT-cost-basis-and-what-D304-and-D305-changed.md"
    assert RECORD.match(embedded).group(1) == "300"

    # And the variant really is present in the tracked set, so the case above is not hypothetical.
    variants = [n for n in basenames if re.match(r"^D0*\d+[a-z][-.]", n)]
    assert variants, "no variant-suffixed record is tracked; this gate is testing a shape that is not here"
