"""Every number in `docs/results/D190-D544.md` is pinned to the artifact it came from (D545).

The page is **hand-written**, which makes it the odd one out in `docs/results/` — every other `.md`
there is emitted by a runner, prose and all. That matters for one specific reason:
`tests/unit/test_quoted_counts_are_current.py` lists `docs/results/` as FROZEN with the reason
*"study ledgers emitted by a runner; regenerating the study rewrites them"*. A hand-written page
dropped in that directory inherits a no-gate exemption written for files a runner owns — **nothing
would ever check its numbers, and nothing would ever rewrite them either.**

So the page brings its own gate, and this is it.

WHY ANCHOR TO `data/*.json` AND NOT TO ANOTHER DOCUMENT
-------------------------------------------------------
`tests/unit/test_writeup.py` — the pattern this file follows — checks `docs/writeup.md` against
`docs/results/*.md`, which are themselves prose. An artifact is regenerated by a runner and already
gated by `scripts/build_data_manifest.py --verify`, so it is the stronger source: if a study is
re-run and a headline moves, the JSON moves and this file goes red.

THE FLOOR, WHICH `test_writeup.py` DOES NOT HAVE
-------------------------------------------------
A `@pytest.mark.parametrize` over an empty list collects nothing and fails nothing. Measured on
`test_writeup.py` before this file existed: emptying its `ANCHORS` takes it from **29 passed to
"3 passed, 1 skipped", exit code 0** — its twenty-six anchor checks vanish silently, in the gate
whose entire job is keeping a document honest. That is the empty-scan defect, and the same floor is
added there.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
PAGE = REPO / "docs" / "results" / "D190-D544.md"

#: Below this the gate is watching a page that has lost its evidence. 20 anchors when written.
MINIMUM_ANCHORS = 14


def _normalized(path: Path) -> str:
    """Unicode minus folded to ASCII hyphen, as `test_writeup.py:73` does."""
    return path.read_text(encoding="utf-8").replace("−", "-").replace("‑", "-")


def _artifact(name: str) -> dict:
    return json.loads((REPO / "data" / name).read_text(encoding="utf-8"))


def _round_trip(value: float, places: int) -> str:
    return f"{value:.{places}f}"


#: (text as it appears on the page, how to recompute it) — the value is a callable so the source
#: is the ARTIFACT, not a second copy of the number.
ANCHORS: list[tuple[str, str, object]] = [
    # --- D279: the lag audit, both artifacts committed side by side -------------------------
    (
        "+2.2498",
        "d279 withdrawn excess_sharpe",
        lambda: "+"
        + _round_trip(
            _artifact("d279_concentrated_summary.WITHDRAWN_lookahead.json")["cells"][
                "S1_short|top25"
            ]["excess_sharpe"],
            4,
        ),
    ),
    (
        "-0.6376",
        "d279 corrected excess_sharpe",
        lambda: _round_trip(
            _artifact("d279_concentrated_summary.json")["cells"]["S1_short|top25"][
                "excess_sharpe"
            ],
            4,
        ),
    ),
    # --- C2b: the enumerated rotation null ---------------------------------------------------
    (
        "+41.81",
        "c2b G2:T2 exact p95",
        lambda: "+" + _round_trip(_artifact("c2b_rotation_audit.json")["cells"]["G2:T2"]["exact"]["p95"], 2),
    ),
    (
        "+35.95",
        "c2b G2:T2 published p95",
        lambda: "+"
        + _round_trip(_artifact("c2b_rotation_audit.json")["cells"]["G2:T2"]["published"]["p95"], 2),
    ),
    (
        "+0.52",
        "c2b G2:T2 exact margin",
        lambda: "+" + _round_trip(_artifact("c2b_rotation_audit.json")["cells"]["G2:T2"]["exact"]["margin"], 2),
    ),
    (
        "+56.82",
        "c2b G1:T1 exact p95",
        lambda: "+" + _round_trip(_artifact("c2b_rotation_audit.json")["cells"]["G1:T1"]["exact"]["p95"], 2),
    ),
    (
        "+68.51",
        "c2b G2:T1 exact p95",
        lambda: "+" + _round_trip(_artifact("c2b_rotation_audit.json")["cells"]["G2:T1"]["exact"]["p95"], 2),
    ),
    # --- D370: symmetry, not draw count ------------------------------------------------------
    (
        "+4.219",
        "d370 symmetric observed",
        lambda: "+" + _round_trip(_artifact("d370_report.json")["symmetric"]["observed"], 3),
    ),
    (
        "+3.617",
        "d370 symmetric p95",
        lambda: "+" + _round_trip(_artifact("d370_report.json")["symmetric"]["p95"], 3),
    ),
    (
        "+0.602",
        "d370 symmetric margin",
        lambda: "+" + _round_trip(_artifact("d370_report.json")["symmetric"]["margin"], 3),
    ),
    (
        "+4.230",
        "d370 asymmetric p95",
        lambda: "+" + _round_trip(_artifact("d370_report.json")["asymmetric"]["p95"], 3),
    ),
    (
        "+3.919",
        "d370 asymmetric observed",
        lambda: "+" + _round_trip(_artifact("d370_report.json")["asymmetric"]["observed"], 3),
    ),
    (
        "-0.311",
        "d370 asymmetric margin",
        lambda: _round_trip(_artifact("d370_report.json")["asymmetric"]["margin"], 3),
    ),
    (
        "+1.562",
        "d370 asymmetric p50",
        lambda: "+" + _round_trip(_artifact("d370_report.json")["asymmetric"]["p50"], 3),
    ),
    (
        "+0.679",
        "d370 symmetric p50",
        lambda: "+" + _round_trip(_artifact("d370_report.json")["symmetric"]["p50"], 3),
    ),
    # --- D466: the component standard, and the numbers that have no artifact -----------------
    (
        "+0.369",
        "d466 K1 net sharpe at micro size",
        lambda: "+" + _round_trip(_artifact("d466_components.json")["components"]["K1"]["sharpe"], 3),
    ),
    (
        "0.322",
        "d466 K1 sharpe SE",
        lambda: _round_trip(_artifact("d466_components.json")["components"]["K1"]["sharpe_se"], 3),
    ),
    (
        "-0.011",
        "d466 K2 net sharpe at micro size",
        lambda: _round_trip(_artifact("d466_components.json")["components"]["K2"]["sharpe"], 3),
    ),
    (
        "+0.031",
        "d466 assembled book sharpe",
        lambda: "+" + _round_trip(_artifact("d466_components.json")["book_K1K2K3"]["sharpe"], 3),
    ),
    # --- D493: the lifecycle sweep -----------------------------------------------------------
    ("448", "d493 cell count", lambda: str(len(_artifact("d493_account_size_lifecycle.json")["cells"]))),
]


@pytest.fixture(scope="module")
def page() -> str:
    return _normalized(PAGE)


def test_the_page_exists_and_says_what_it_is(page):
    """A hand-written page in a runner-owned directory must say so on its face, and carry the
    date that stands in for the regeneration it will never get."""
    assert "Hand-written" in page
    assert "2026-09-18" in page


def test_the_anchor_list_has_not_been_emptied():
    """THE FLOOR. `@pytest.mark.parametrize` over `[]` collects nothing and fails nothing, which
    is how a gate becomes decorative without anyone noticing."""
    assert len(ANCHORS) >= MINIMUM_ANCHORS, (
        f"{len(ANCHORS)} anchors, below the floor of {MINIMUM_ANCHORS}. Either the page lost its "
        f"evidence or this list was trimmed; both read as a pass from the parametrized test."
    )


@pytest.mark.parametrize("quoted,what,recompute", ANCHORS, ids=[a[1] for a in ANCHORS])
def test_every_quoted_number_matches_its_artifact(page, quoted, what, recompute):
    """The number on the page, and the number in `data/`, must be the same string."""
    measured = recompute()
    assert measured == quoted, (
        f"{what}: the artifact now reads {measured!r} but the page quotes {quoted!r}. A study was "
        f"re-run and a headline moved — update docs/results/D190-D544.md, it is now lying."
    )
    assert quoted in page, f"docs/results/D190-D544.md no longer quotes {quoted!r} for {what}"


def test_the_page_states_that_nothing_is_at_capital(page):
    """The directive that shaped this page: a market-findings framing invites 'so what did you
    make', and the answer belongs in the opening rather than the footer."""
    assert "Nothing here is at capital" in page
    head = page[: page.index("## Three findings about trading")]
    assert "at capital" in head, "the disclosure moved below the first finding"


def test_the_page_keeps_the_two_theorems_apart(page):
    """C2b's centre-bias theorem and D373's 2-SE UNRESOLVED band are different claims, and this
    record's own first draft conflated them. The distinction is load-bearing enough to pin."""
    assert "2 SE" in page and "UNRESOLVED" in page
    assert "They are not the same claim." in page


def test_the_unsourceable_numbers_are_named_as_such(page):
    """D466's 0.62 / 0.42 / 0.91 have no committed artifact — they were computed outside the
    runner. The page may quote them ONLY as withdrawn, and must say they cannot be sourced."""
    for orphan in ("0.62", "0.42", "0.91"):
        assert orphan in page, f"the page stopped naming the withdrawn figure {orphan}"
    assert "no artifact" in page
    assert re.search(r"cannot be sourced", page), "the page must say why those three differ"
