"""Every decision number on disk appears in `docs/decisions/README.md`.

**This test exists because the index silently stopped being true for 251 numbers.** It was a
curated table of D1–D284; the directory kept growing to D537, and nothing noticed — not a test,
not a script, nothing read the file programmatically at all. Two other documents went stale
alongside it, each telling a contributor to take the next decision number from a table that had
not moved in months: `docs/RULES.md` said D283, the index itself said D280.

The register half is generated by `scripts/build_decision_register.py`. This is what makes the
generation load-bearing rather than a one-off tidy-up: add a record without regenerating and the
suite goes red.

It deliberately asserts **coverage, not format**. The curated half is inconsistent by nature —
17 of its rows carry two cells, 8 carry five to eight because prose contains unescaped `|` — and
a format assertion would either fail on the existing table or force a rewrite of 290 hand-written
summaries nobody asked for.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DECISIONS = REPO / "docs" / "decisions"
INDEX = DECISIONS / "README.md"


def _numbers_on_disk() -> set[int]:
    return {
        int(re.match(r"D(\d+)", path.name).group(1))
        for path in DECISIONS.glob("D*.md")
        if re.match(r"D\d+", path.name)
    }


def _numbers_in_index() -> set[int]:
    # Matches both halves: curated rows `| [D01](…)` and register rows `| D537 | … |`.
    return {int(n) for n in re.findall(r"\|\s*\[?D0*(\d+)", INDEX.read_text(encoding="utf-8"))}


def test_every_decision_number_is_listed_in_the_index():
    missing = sorted(_numbers_on_disk() - _numbers_in_index())
    shown = f"{missing[:20]}{' …' if len(missing) > 20 else ''}"
    assert not missing, (
        f"{len(missing)} decision number(s) are not in docs/decisions/README.md: {shown}. "
        "Regenerate the register: `python scripts/build_decision_register.py --write`."
    )


def test_the_index_does_not_list_numbers_that_do_not_exist():
    """The other direction — a row pointing at a record that was deleted or renamed.

    `scripts/check_doc_links.py` catches a broken *link*; this catches a row whose number has no
    file at all, which is the shape a renumbering would leave behind.
    """
    phantom = sorted(_numbers_in_index() - _numbers_on_disk())
    assert not phantom, f"index lists decision numbers with no record on disk: {phantom}"
